conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
Atum fails to write the Additional Information added at the end of each job to the _INFO file. This happens because we rely on the destination being inferred from the where the resulting parquet is being written. This works like a charm, but we have some additional info that we want to add after the final write. Atum writes outstanding checkpoints on exit, but fails to do so without an explicit destination for the _INFO file (can't infer).
This is a fix, calling Atum to explicitly write the _INFO file until we get Atum to handle this automatically.
=> Patch missing additional info value from _INFO file

pom.xml
Moving to free bintray account as trial period is ending. This change requires an update to our repository URL.
=> Update absa bintray

standardization/src/test/scala/za/co/absa/enceladus/standardization/samples/TestSamples.scala
when a time stamp is initialized with Long it is initialized with UNIX time which is zoneless since it denotes a period of time passed after epoch so removed multiplication with long and added long value to convert to timestamp, so the test case can be executed locally
=> #68 Timezone bug fix for TestSamples

standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala
replace usage of .foldLeft over columns to .select(map...) where it is critical. Tested on synthetic and real data: standardisation takes linear time on the number of columns (polynomial previously). For the real dataset with 717 columns the time has reduced from 3 hours to 4 minutes.
=> #26 Performance optimisation for standardisation

scalastyle-config.xml
Scalastyle is already off for tests, style warnings are not raised there. You may need to change your IDE code-inspection settings though (these are two separate issues). 
In IntelliJ:
=> 139 Turn off scalastyle for tests

testutils/src/main/scala/za/co/absa/enceladus/testutils/datasetComparison/ComparisonJob.scala
Adds an error column to the data set, listing all the places where differences were found in two datasets. This works only for flat structures right now
Many thanks to @yruslan for help with adding and concatenating the errCol
=> Add errCol to comparison job

menas/ui/components/schema/schemaMain.controller.js
The issue was a missing CSRF request header (since we switched from embedding in in the HTML document to passing it via response header)
=> #159 Fix csrf token request header for shcema upload

menas/ui/components/dataset/datasetMain.controller.js, menas/ui/service/DatasetService.js, menas/ui/service/RuleService.js
- Assign correct order number to each conformance rule
**1. Run tests:**
- go to enceladus dir
- mvn -DskipTests clean package
- mvn verify
- **Expected result**: All tests should pass
**2. Create/Remove rules:**
- Run application
- Log in 
- Go to Dataset tab 
- Pick one of the datasets (or Create new dataset)
- Go to Conformance Rules
- Create at least 3 rules 
- **Expected result**: Each rule should have correct order number in DB (Create A, Create B, Create C => A.order:0, B.order:1, C.order:2). They should display in correct order.
- Delete middle rule
- **Expected result**: Each rule should have correct order number in DB (Create A, Create B, Create C => A.order:0, B.order:1, C.order:2 => Delete B => A.order:0, C.order:1). They should display in correct order.
- Delete first rule
- …
=> #149 Persist conformance rules order

conformance/pom.xml
The issue stems from the fact that the `enceladus-dataModel` dependency in the conformance job should be transitive from the `enceladus-dao` dependency. `enceladus-dao` shades the jackson library in order to comply with Spring's jackson version without conflicting with Spark's jackson version. When the `enceladus-dataModel` dependency is explicitly present, the jackson annotations  on the models are unshaded and the shaded `enceldaus-dao` jackson does not recognize them, hence fails to deserialize.
=> 207 Fix conformance deserialization issue

menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/add.fragment.xml, menas/ui/components/dataset/conformanceRule/MappingConformanceRule/joinConditions.fragment.xml, menas/ui/components/dataset/conformanceRule/upsert.controller.js, menas/ui/components/dataset/conformanceRule/upsert.fragment.xml, menas/ui/components/dataset/datasetMain.controller.js, menas/ui/components/mappingTable/mappingTableMain.controller.js, menas/ui/components/mappingTableSelector.fragment.xml, menas/ui/components/schemaFieldSelector.fragment.xml, menas/ui/service/MappingTableService.js, menas/ui/service/RuleService.js
Be gentle! :D 
- Update conformance rules ui implementation (New feature)
- A lot of small fixes and refactorings:
- Update/Create conformance rules code moved to fragment's controller
- ConcatenationConformanceRule and MappingConformanceRule fragment redesigne
- List is used instead of in code generated fragment parts
- New button with remove input fields functionality
- Removed rule specific logic from RuleService
- Others ...
**1. Run tests:**
- go to enceladus dir
- mvn -DskipTests clean package
- mvn verify
- **Expected result**: All tests should pass
**2. Create rule for each rule type:**
- Run application
- Log in 
- Go to Dataset tab 
- Pick one of the datasets (or Create new dataset)
- Go to Conformance Rules
- Create rule 
- **Expected result**: 
- Rule should be …
=> #80 Update conformance rules ui implementation

conformance/pom.xml, menas/pom.xml, pom.xml, standardization/pom.xml
This makes build fail if there are no 'application.conf' inside Standardization and Conformance resources folder.
This is likely to require changes on Jenkins side.
=> #215 Make Standardization and Conformance build fail if there is no application.conf

dataModel/pom.xml
There was a superfluous `mongo-scala-driver` dependency in the `dataModel` module, which conflicted with the `mongo-java-driver` used by spline.
Many thanks to @wajda and @yruslan for the help in figuring this out!
=> #233 Fix Spline initialization

conformance/pom.xml, menas/pom.xml, pom.xml, standardization/pom.xml
Let's replace the enforcer plugin, which fails the build if the
application.conf is missing from the main resources.
Rather let's materialize the template on the first build, which
will provide reasonable defaults without necessary providing
custom configs while preserving existing files.
This means that people should be able to clone and build the
project (incl tests) out of the box.
=> #256 Replace maven enforcer with antrun copy task

Jenkinsfile
As there has been an update to automatically moved .template files, the prepare step is no longer needed as it just calls a function which has the same behaviour.
=> #261 Removed prepare step in Jenkinsfile

menas/ui/components/dataset/conformanceRule/upsert.controller.js, menas/ui/components/dataset/datasetMain.controller.js, menas/ui/components/mappingTable/mappingTableMain.controller.js, menas/ui/components/schema/schemaMain.controller.js
Perform deep copy of the current entity objects to ensure
that two-way binding doesn't affect the un-saved changes.
=> #11 View updates even from canceled edit window

testutils/pom.xml, utils/src/main/scala/za/co/absa/enceladus/utils/types/EnceladusDateParser.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/Format.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/DateTimeValidators.scala, utils/src/test/scala/za/co/absa/enceladus/utils/types/EnceladusDateParserSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/types/FormatSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorsSuite.scala
* DateTimeValidators changes to use the same conversion class as the standardization itself
* EnceladusDateParser class now has format method to convert TO string
* Unit tests for DateTimeValidators
* Enhanced unit tests for Format and EnceladusDateParser
=> #186: Epoch standardisation doesn't pass with pattern "epoch"

menas/ui/components/mappingTable/addMappingTable.fragment.xml, menas/ui/components/mappingTableSelector.fragment.xml, menas/ui/components/schemaSelector.fragment.xml
This was probably intended to provide a popup view of the selected schema, but was never implemented. It doesn't make sense to have a functionless button until we do implement this feature (if we do, we should have create a task for it).
=> #178 Remove unused button from add/edit dialogs

Jenkinsfile
This is a quick update to reversion the artifacts built during deploy.
As it stands, every artifact is version 0.99-SNAPSHOT, which isn't great.
This will reversion them on deployment to Nexus/Test Servers with the Git commit ID for tracking of actual changes.
=> 293: Updated Jenkinsfile to reversion artifacts with Git commit ID before deploy

menas/src/test/scala/za/co/absa/enceladus/rest/services/BaseServiceTest.scala, menas/src/test/scala/za/co/absa/enceladus/rest/services/VersionedModelServiceAuditTest.scala, menas/src/test/scala/za/co/absa/enceladus/rest/services/VersionedModelServiceTest.scala
This is a workaround to fix AWS builds that fail from time to time.
It's just the one unit test that takes long `"Test getAuditTrail TestSchema1"`, on my machine it need a 15ms timeout to pass consistently. We might need to figure out why it's 20 times slower on AWS.
=> #312 Increase timeout to 500ms for 'Test getAuditTrail TestSchema1'

README.md
This is a build status badge which will show the current build status on Jenkins for the develop branch.
Users can view the last build on successful login to Jenkins. 
No details can be seen until the user logs in.
=> Added Build Status Badge for Develop Branch

menas/src/main/scala/za/co/absa/enceladus/menas/controllers/SchemaController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/SparkMenasSchemaConvertor.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/model0/Schema.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/model0/SchemaField.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/model0/Serializer.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/model0/VersionedModel.scala, menas/src/test/scala/za/co/absa/enceladus/menas/schema/SchemaConvertersSuite.scala
So this is actually not a separate conversion tool but the support of old Menas schema JSON format support by the schema uploader.
=> Add support for the old Menas JSON schema format for schema upload

testutils/src/main/scala/za/co/absa/enceladus/testutils/HelperFunctions.scala, testutils/src/test/scala/za/co/absa/enceladus/testutils/HelperFunctionsSuite.scala
* Within the function US Locale is enforced
* Less type conversions
* Using object constants instead of computing them on every function run
* Using existing function on Integral implicit instead of defining own function of same result
* 0 milliseconds doesn't result in empty string anymore
* Swap of parameters in unit tests assert (to match expected and actual)
=> #408: prettyPrintElapsedTime in different Locale

conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala, conformance/src/test/scala/za/co/absa/enceladus/samples/TradeConformance.scala, conformance/src/test/testData/employee/2017/11/01/_INFO, pom.xml
Atum 0.2.1 writes all control metrics as strings avoiding tricky number parsing issues.
The model of metrics still contain Any to retain compatibility with _INFO files provided
by source systems and for backward compatibility.
=> #415 Fix checkpoint measurements serialization by updating Atum to 0.2.1

standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationCommon.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala, standardization/src/test/resources/data/patients.json, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromBooleanTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDateTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDecimalTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDoubleTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromLongTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromStringTypeSuite.scala, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromTimestampTypeSuite.scala
* Splitting up too long `StandardizationInterpreter.standardize` method
* Removed usage of `Random` for temporary error column names to decrease chance of name clash
* Removed var property within `StandardizationInterpreter` object
* Two unit tests to cover the refactoring doesn't change the logic
* `unpath` function to own trait
* `TypeParser` suits renamed per agreement from CQC
=> #412: Refactor StandardizationInterpreter

menas/ui/components/home/landingPage.controller.js
- This seems to be a bug produced by PR refactoring, where
"this" context was wrongly passed to showMaster method
=> #504 Menas home page tiles throw an error

menas/pom.xml, pom.xml, standardization/pom.xml, standardization/src/main/scala/za/co/absa/enceladus/standardization/CmdConfig.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/CobolOptions.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
This implementation is mostly for getting Cobrix dependencies.
COBOL options, like location of a copybook, etc will go to properties of dataset.
=> #440 Add a support for the simplest use case of COBOL data format

pom.xml, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, utils/src/main/scala/za/co/absa/enceladus/utils/performance/PerformanceMetricTools.scala
These metrics will help gethering statistics about data processed by Enceladus.
The list of new metrics: enceladus_info_date, enceladus_info_version,
raw_record_count, std_record_count, conform_record_count.
=> #463 Add new metrics to Atum's metadata

conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/TestRuleBehaviors.scala, menas/src/main/scala/za/co/absa/enceladus/menas/repositories/OozieRepository.scala, menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, testutils/src/test/scala/za/co/absa/enceladus/testutils/datasetComparison/ComparisonJobTest.scala, utils/src/main/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicits.scala, utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/LoggerTestBase.scala, utils/src/test/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicitsSuite.scala
* simplifying the expression for enceladus_info_date, avoiding the source of problems (DynamicConformanceJob.processResult)
* Ensuring simpleDateFormat is created only after TimeZoneNormalizer logic is executed
* LoggerTestBase enhancement
* DynamicConformanceJob.main broke up into subroutines to make it shorter (hopefully clearer too)
* conformanceRuleShouldMatchExpected uses logger instead of println (not related to bug, spotted on bug investigation)
* Some stylistic adjustments
(Source of the bug - SimpleDateFormat was created before TimeZoneNormalizer logic, which bound that instance to the system time zone.
=> #458: Column enceladus_info_date does not respect timezones

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/UserInfoController.scala, menas/ui/components/app.controller.js, menas/ui/components/run/runDetail.controller.js, menas/ui/index.html
- uses the fixed version resolver in Spring
- index first gets the version from the API
- then programmatically loads all the dependencies with the
version prefix
- only on load of the last dependency do we initialize the
component container (which is configured to load all
local resources with the version prefix)
This changes requires the 3 new properties in application
properties.
@GeorgiChochov any idea if the webjar locator can be configured for the versioned resources somehow?
=> #636 Automatically invalidate static resources on new deployment

menas/pom.xml, menas/ui/generic/model.js, menas/ui/service/GenericService.js, menas/ui/service/RestDAO.js, pom.xml
This fixes the bug observed, but does not address the underlying issue. Why did `${name}` and `${version}` get replaced with `project.name` and `project.version`. To be addressed in a follow-up PR for this task...
=> #685 Fix broken schema file export

conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala, menas/src/main/scala/za/co/absa/enceladus/menas/SparkConfig.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, testutils/src/main/scala/za/co/absa/enceladus/testutils/datasetComparison/ComparisonJob.scala, testutils/src/main/scala/za/co/absa/enceladus/testutils/e2eSparkRunner/E2ESparkRunner.scala, testutils/src/main/scala/za/co/absa/enceladus/testutils/infoFileComparison/InfoFileComparisonJob.scala, testutils/src/main/scala/za/co/absa/enceladus/testutils/rest/RestRunnerJob.scala, utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkTestBase.scala, utils/src/main/scala/za/co/absa/enceladus/utils/time/TimeZoneNormalizer.scala
* TimeZoneNormalizer got rid of `lazy` property
* Calls to TimeZoneNormalizer, especially TimeZoneNormalizer.normalizeJVMTimeZone, moved to early stages of execution
=> #458: Early Timezone normalization

pom.xml, standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromBooleanTypeSuite.scala, utils/src/main/scala/za/co/absa/enceladus/utils/time/EnceladusDateTimeParser.scala, utils/src/test/scala/za/co/absa/enceladus/SchemaValidationSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/time/EnceladusDateTimeParserSuite.scala
* Match EnceladusDateTimeParser lenient setting to Spark's
* Extra test on leniency
* Fixed SchemaValidationSuite tests
* Ensuring Maven runs tests in UTF-8
=> #707: Parsing leniency differs between EnceladusDateTimeParser and Spark

utils/src/main/scala/za/co/absa/enceladus/utils/error/ErrorMessage.scala, utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala, utils/src/main/scala/za/co/absa/enceladus/utils/fs/FileSystemVersionUtils.scala, utils/src/main/scala/za/co/absa/enceladus/utils/implicits/ColumnImplicits.scala, utils/src/main/scala/za/co/absa/enceladus/utils/performance/PerformanceMeasurer.scala, utils/src/main/scala/za/co/absa/enceladus/utils/schema/SchemaUtils.scala, utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkJobRunnerMethods.scala, utils/src/main/scala/za/co/absa/enceladus/utils/transformations/ArrayTransformations.scala, utils/src/main/scala/za/co/absa/enceladus/utils/transformations/DeepArrayTransformations.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/TypePattern.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/SchemaPathValidator.scala, utils/src/test/resources/log4j.properties, utils/src/test/scala/za/co/absa/enceladus/FsUtilsSpec.scala, utils/src/test/scala/za/co/absa/enceladus/utils/transformations/ArrayTransformationsSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/transformations/DeepArrayErrorTransformationSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/transformations/DeepArrayTransformationSuite.scala
* Adhere to Scalastyle
* Follow some best-practices:
** typed implicits
** types declared for public members
** limit implicit conversions and if mark them
* Parameterless function as type
* setup logging for tests - style, filtering
* remove direct output to console (println, Dataframe.show, etc)
=> #718: Decrease the size of the build log - module Utils

conformance/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala, conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
This is caused by wrong explodeContext being used when a Catalyst
workaround is applied. This led to an additional array explosion
inside an explosion context, which was not actually applied.
That lead to actual explosions not being collapsed.
=> #788 Fix experimental mapping rule non-deterministic bug

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/ConfigurationController.scala, menas/src/test/resources/application.properties, menas/ui/components/home/landingPage.controller.js, menas/ui/components/home/landingPage.view.xml, menas/ui/components/login/loginDetail.controller.js, menas/ui/components/login/loginDetail.view.xml, menas/ui/service/RestDAO.js
With this PR and with advice from @GeorgiChochov (BTW many thanks!!) I created a controller `ConfigurationController`. This controller could, later on, hold more than just the environment name, but we could even move `menasVersion` to it from `UserInfoController`.  `ConfigurationController` is for the API calls that do not require authentication.
=> #826 Add environment name to login and home page

menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
This probably worked before the entity clean up, where the dates would be sent along with the update.
=> #857 Update schedule fails, trying to write null into dateCreated

conformance/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleInterpreter.scala, conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleSuite.scala, conformance/src/test/scala/za/co/absa/enceladus/samples/NegationRuleSamples.scala, utils/src/main/scala/za/co/absa/enceladus/utils/schema/SchemaUtils.scala, utils/src/test/scala/za/co/absa/enceladus/utils/schema/SchemaUtilsSuite.scala
* Negation Rule uses Defaults.getGlobalDefaultWithNull instead of Defaults.getGlobalDefault
* Support for Arrays in Arrays in SchemaUtils
* Unified similar code in SchemaUtils
* added getStructField and fieldExists into SchemaUtils
* Updated and enhanced UTs
=> #822: Use defaultWithNull in Conformance

scripts/bash/run_enceladus.sh
- Added statement to return exit status of the last failed command in the subshell pipeline running spark submit
- Spark submit subshell exit status is propagated to the scripts final exit status and is printed to the user in case of client deploy mode
=> Issue #893: The convenience scripts should always propagate spark's status codes

menas/src/main/scala/za/co/absa/enceladus/menas/controllers/SchemaController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/SparkMenasSchemaConvertor.scala, menas/src/test/scala/za/co/absa/enceladus/menas/utils/converters/SparkMenasSchemaConvertorSuite.scala, menas/ui/components/schema/schemaDetail.controller.js, menas/ui/service/ResponseUtils.js
* Parsing the schema fields' metadata, that they are all of type String
* Reordering the database save operations, so that the parsing is done before
* Enhanced feedback info in case parsing fails
=> #799: Uploading schema with default value having integer breaks the schema

conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
Run E2E locally. Works fine. Found out performance.PerformanceMetricTool also checks this.
```
19/09/19 13:47:25 ERROR performance.PerformanceMetricTools$: No successful records after running the Spark Application. Possibly the schema is incorrectly defined for the dataset.
```
I know code duplicates itself but there is #483 already for it. I would not like to set some weird standard that would later "bully" the person doing #483.
=> 909 Allow processing empty datasets

scripts/bash/enceladus_autocompletions.sh
An autocompletion script for Enceladus's standardization and conformance
Expects
- `"$PATH_TO_SCRIPTS/run_standardization.sh"` - to be path to executable standardization script
- `"$PATH_TO_SCRIPTS/run_conformance.sh"` - to be path to executable conformance script
=> 926 Add bash completions

conformance/pom.xml, dao/pom.xml, dataModel/pom.xml, examples/pom.xml, external/fixedWidth/pom.xml, external/kafka/pom.xml, menas/pom.xml, migrations-cli/pom.xml, migrations/pom.xml, pom.xml, selenium/pom.xml, standardization/pom.xml, standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala, testutils/pom.xml, utils/pom.xml
* to produce the output data frame the desired schema for renaming is used, which contains the metadata
* to prevent error column from being dropped it's added explicitly
=> #398: sourcecolumn metadata value doesn't work

migrations/src/main/scala/za/co/absa/enceladus/migrations/framework/dao/ScalaMongoImplicits.scala
Adaptation of argument list by inserting () has been deprecated: this is unlikely to be what you want.
signature: Promise.success(value: T): Promise.this.type
given arguments: <none>
after adaptation: Promise.success((): Unit)
=> #962 Fix a deprecation warning.

menas/pom.xml, menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala, menas/src/main/scala/za/co/absa/enceladus/menas/health/HdfsHealthChecker.scala, menas/src/main/scala/za/co/absa/enceladus/menas/health/MongoHealthChecker.scala
Includes the following endpoints:
`GET /admin` - list of all actuator endpoints - requires authentication (once permissions is sorted this should be stricter #30)
`GET /admin/heapdump` - downloads a heapdump of the application - requires authentication
`GET /admin/threaddump` - list of the threaddump of the application - requires authentication
`GET /admin/loggers` - list of all the application loggers and their log levels - requires authentication
`POST /admin/loggers/{logger}` - change the log level of a logger in runtime - requires authentication
`GET /admin/health` - get a detailed status report of the application's health - DOES NOT require authentication :
```json
{
"status": "UP",
"details": {
"HDFSConnection": {
"status": "UP"
},
"MongoDBConnection": {
"status": "UP"
}, …
```
=> 884 Enable Spring Boot Actuator

menas/src/main/scala/za/co/absa/enceladus/menas/repositories/RunMongoRepository.scala
This is a workaround we won't need after #273. As it stands the current Runs Navigation is unusable. The only reason we should keep this endpoint alive is because people might be using it. We should mark it deprecated and remove it in version 2.0.0
=> 1053 Allow disk use for get all run summaries query

README.md
* Removed *How to use* chapter
* Fixed some typos
* Links to headers changed to standard and removed anchor names
* some table alignments for better readability in text-only display
=> #1067: Remove Usage chapter from README.md

.gitignore, Gemfile, README.md, _docs/1.0.0/usage-schema.md, utils/create_docs.rb, utils/get_release_notes.rb, utils/get_release_notes/issue.rb, utils/get_release_notes/opt_parser.rb, utils/get_release_notes/release.rb, utils/get_release_notes/release_notes.rb, utils/resources/get_release_notes.conf.template
1. I did a quick fix of the non-formating json in schema, it bugged me so I just used a gist to do it for now. We will solve later.
2. `create_docs.rb` creates a full folder and goes over every file and changes the versions. Needs an argument and that is the new version. Other things it gets by itself. In the future, I might do this automatically as well.
3. `get_release_notes.rb` connects to ZenHub and GitHub and automatically generates release notes. It takes the latest release, collects issues and then collects comments from these issues that start with `Release Notes`. So basically now you have to comment release note as:
```
Release Notes
This fixes this thing and the other. 
I can even use special formating characters here.
```
This should close #1039
=> 1039 Add convinience scripts for gh pages

utils/src/main/scala/za/co/absa/enceladus/utils/error/ErrorMessage.scala
* The codes are actually not in conflict, just the ranges overlap
* Separating the codes into a dedicated object where they are next to each other should make it clear they don't conflict and make it harder to create a conflict in future
=> #1128: Conformance and Standardization error codes overlap

spark-jobs/src/main/resources/application.conf.template, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/FeatureSwitches.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/ThreeStateSwitch.scala, spark-jobs/src/test/resources/application.conf, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/ArrayConformanceSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/ChorusMockSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/LiteralJoinMappingRuleTest.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/MappingRuleBroadcastSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/MappingRuleSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/RuleOptimizationSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/NestedTestCaseFactory.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
* auto - will always use the broadcasting strategy.
* never - never user the broadcasting strategy.
* auto - use the strategy depending on the size of the mapping table.
=> #1129 Add a configuration switch to control the broadcasting strategy  for mapping rules.

utils/get_release_notes/issue.rb, utils/get_release_notes/release.rb
- add an option for \r on the end of lines
- actually invoke the API for getting issue comments
=> 1170 fix release notes generation

menas/pom.xml, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/RestExceptionHandler.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/SchemaController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/models/rest/errors/RemoteSchemaRetrievalError.scala, menas/src/main/scala/za/co/absa/enceladus/menas/models/rest/exceptions/RemoteSchemaRetrievalException.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/BaseRestApiTest.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/SchemaApiIntegrationSuite.scala, menas/src/test/scala/za/co/absa/enceladus/menas/package.scala, menas/src/test/scala/za/co/absa/enceladus/menas/utils/parsers/SchemaParserSuite.scala, menas/ui/components/schema/schemaDetail.controller.js, menas/ui/components/schema/schemaDetail.view.xml
- Tested against local HTTP server, e.g. `http://localhost:8000/avro_users-v1-struct.json`
- also works against a REST client with the `x-www-form-urlencoded` content type, provided there is an appropriate `X-CSRF-TOKEN` present.
- integtest updated to cover the `/remote` load variant. WireMock HTTP server mocking is used there, including mocking proper mime types of the served files.
`schemaDetail.controller`:
- the UI also works, but jQuery ajax call is used (`handleRemoteUrlSubmit`) whose response is quite similar, but not too similar to the uploading variant (`handleRemoteLoadComplete` vs `handleUploadComplete` - not sure it pays off to generalize. Or is there a way to convert one response to the type of the other?)
- also tested to work with `Avro Schema (avsc)` and URL …
=> #1163 Loading Schema from URL

spark-jobs/src/main/resources/application.conf.template
In addition, make the size of mapping table to broadcast to 10 MB so that
if many mapping tables are used there won't be out of memory issues.
=> #1157 Use the new optimized implementation of mapping rule by default

data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/RunFactory.scala, plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/factories/DceControlInfoFactory.scala, pom.xml, spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/EventListenerMenas.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/MenasPlugin.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
This fixes the attempt to send control info when the Kafka producer is already closed.
=> #1277 Use onApplicationEnd event to close Enceladus plugins

spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/common/version/SparkVersionGuard.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
As pointed out [here](https://github.com/AbsaOSS/enceladus/pull/1297/files#r413867037), only the default Spark minimum of `2.4.2` will be enforced to Hyper Conformance
=> #1285 Fixes wrongly enforced minimum Spark version with the default

_docs/1.0.0/usage-schema.md, _docs/2.0.0/usage.md, _docs/2.0.0/usage/config.md, _docs/2.0.0/usage/schema.md
_Usage > Configuration_ page was started, brief info about general config and overriding it has been added (mainly for the sake of documenting the `enceladus.recordId.generation.strategy`)
closes #1294
=> 1294 config docs

_includes/header.html, _posts/2020-05-15-release-2.5.0.md
* Links fixed
* Better typography
* header.html `class` fix
=> 1348: Links in Release notes v2.5.0 doesn't work

spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformanceAttributes.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/datasource/PartitioningUtils.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/streaming/InfoDateFactory.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/streaming/InfoDateFactorySuite.scala
* If transformer.hyperconformance.report.date is specified, it will be used
* If transformer.hyperconformance.event.timestamp.column is specified, the event date derived from it will be used
* Otherwise the processing date will be used.
Closes #1331 and closes #1333
=> #1333 Change the way 'enceladus_info_date' is generated for streaming jobs

menas/src/main/scala/za/co/absa/enceladus/menas/controllers/SchemaController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/services/AttachmentService.scala, menas/ui/components/schema/schemaDetail.controller.js
- AVSC is always saved and exported with the same mime-type: `application/vnd.schemaregistry.v1+json`
- means attachment version is now in line with the schema version (shown in Menas)
// edit: will need to create something more convoluted, see comments.
The following MongoDB script can be used to remap means attachments version, provided there are no holes (i.e. means without and with the bug was not used over the same persistence and the ids are not e.g. `2, 3, (missing 4 here) 5, 6`):
- `2, 3, 4` -> `2, 3, 4` (no change, all should be already correct)
- `3, 4, 5, 6` -> `2, 3, 4, 5` (all -1, all should be correct)
- `2, 3, 5, 6` -> `2, 3, 5, 6` (no change, does not work for version sequences with holes, so the second half of the version would stay incorrect)
```javascript …
```
=> #1234 export file fix, menas attachment version fix

README.md, menas/pom.xml, menas/src/main/scala/za/co/absa/enceladus/menas/utils/parsers/SchemaParser.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/SchemaApiIntegrationSuite.scala, menas/src/test/scala/za/co/absa/enceladus/menas/utils/parsers/SchemaParserSuite.scala, pom.xml, spark-jobs/pom.xml, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/CobolOptions.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StdCmdConfig.scala, spark-jobs/src/test/resources/log4j.properties, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationCobolAsciiSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationCobolEbcdicSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/fixtures/TempFileFixture.scala
This adds the support of fixed-width text files when using 'cobol' as raw format.
The only thing that needs to be provided is a copybook. But it is easy for such formats:
```
01  RECORD.
05  A        PIC X(1).
05  B        PIC X(5).
05  C        PIC X(10).
05  FILLER   PIC X(1).
```
Each field defines just the size.
In order to load ASCII files you need to use `--cobol-encoding ascii` (`ebcdic` is Cobrix default). You can specify the charset the normal way using `--charset`.
Since fixed-with text files contain a lot of leading or trailing spaces, users want to control how these spaces will be handled. Use `--cobol-trimming-policy` for that. It can be `none`, `left`, `right` or `both` (Cobrix default).
=> #1353 Add support for ASCII for 'cobol' raw format.

menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_BinarySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/standardizationInterpreter_RowTypes.scala, utils/src/main/scala/za/co/absa/enceladus/utils/schema/MetadataKeys.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/Defaults.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala, utils/src/main/scala/za/co/absa/enceladus/utils/udf/UDFLibrary.scala, utils/src/main/scala/za/co/absa/enceladus/utils/udf/UDFNames.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/SchemaPathValidator.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationException.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/field/BinaryFieldValidator.scala, utils/src/test/scala/za/co/absa/enceladus/SchemaPathValidatorSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/types/TypedStructFieldSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/validation/field/BinaryValidatorSuite.scala
`BinaryType` support added for Enceladus
- encoding in metadata added, supported values are `base64` and `none`. No encoding behaves like `none` (taking strings as-is and just casting them to binary)
- default value follows the encoding set (and is validated to be valid base64 string if base64 encoding is used)
- test cases extended.
- Standardization run ok with a custom binary field in the input (as parquet)
- Conformance UI enriched by allowing `binary` for the _CastingConformanceRule_.
- Tested Conformance with such a rule to cast "binary <-> string": successfully
- default can be provided in the metadata (always encoded as base64):
- having input for Standardziation with a `null`-containing binary field and a schema that disallows null for this column in standardization:
```json
{ …
```
=> #1235 BinaryType support in enceladus

spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/PlainSchemaGenerator.scala, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_data.txt, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_trimmed.txt, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_schema.json, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationFixedWidthSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/PlainSchemaGeneratorSuite.scala
This PR should fix the previously working `fixed-width` format. It is just adding metadata to a stringified schema and adding `columnNameOfCorruptRecord`. Current `fixed-width` does not support that, it can be added when we revive the library.
NB: The expected files have 2 extra new lines because `.show` generates 2 extra newlines.
Closes #1409
RN Comment: Fixed-width format works again.
=> 1409 Fix fixed width format

spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/streaming/InfoDateFactory.scala
* So that we can identify records in the published topic where casting
of event time column to date has failed. 'enceladus_info_date' will
be empty in this case.
=> #1382 Change event-time based enceladus_info_date population strategy.

menas/ui/service/EntityDialog.js
Just a UI fix that fixes the non-disappearing error in HDFS path during Dataset/Mapping table creation/edition
Closes #1432 
RN: Fix Error message not disappearing from HDFS paths during Dataset/Mapping table creation/edition
=> 1432 Fix Menas HDFS path error always showing

menas/Dockerfile
=> 1424 Add Menas Dockerfile

spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Returns the `logEffectiveConfigProps` 
Fixes #1474 
RN: Fixes properties logging at the start of each spark job
=> 1474 Fix conf not logging at the start

spark-jobs/pom.xml, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationPropertiesProvider.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/config/StandardizationConformanceConfig.scala, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_data.txt, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt, spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_with_nulls.txt, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationFixedWidthSuite.scala
Implementation of new FixedWidth project in Enceladus
Added charset, treatEmptyValuesAsNulls and nullValue as spark-job switches
Fixes #1393 
RN: Update version of FIxedWidth and add charset, treatEmptyValuesAsNulls and nullValue options.
=> #1393 Add new fixed width project

scripts/bash/run_enceladus.sh
- option --empty-values-as-nulls
- option --null-value
Closes #1501
RN: Update Helper scripts with `--empty-values-as-nulls` and `--null-value`
=> #1501 Update convenience scripts

menas/ui/service/EntityValidationService.js
This is a temporary solution. We currently experiment with
many forms of URLs, and having a regex there now slows us down.
Closes #1503
=> #1503 Remove HDFS url Validation

_data/configuration_2_0_0.yml, _docs/2.0.0/usage/run.md, _docs/2.0.0/usage/standardization-formats.md
* `--null-value` command line parameter added to csv format
* sorted and added missing Standardization command line parameters
* `conformance.autoclean.standardized.hdfs.folder` description added to configuration documentation
=> 1520: Add null-value option to csv format (documentation)

spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/StandardizationAndConformanceJob.scala
This change directly addresses #1538 - now both `process*Result` methods return `Unit` and thus make any further post-processing routines to reload data from FS as originally intended. (i.e. prohibit using "returned" dataframe to be used)
The rereading is deliberate to ensure that the same data that is being post-processed are already written to the output location and the postProcessing could not be affected by any kind of plan-rerun that could result in newly computed data (this is especially a concern if the output is unstable).
=> #1538 postProcessing reread output - normalization

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/models/rest/errors/RemoteSchemaRetrievalError.scala, menas/src/main/scala/za/co/absa/enceladus/menas/services/SchemaRegistryService.scala, menas/ui/components/schema/schemaDetail.controller.js, utils/src/main/scala/za/co/absa/enceladus/utils/config/ConfigUtils.scala, utils/src/main/scala/za/co/absa/enceladus/utils/config/SecureConfig.scala, utils/src/test/scala/za/co/absa/enceladus/utils/config/SecureConfigSuite.scala
The schema registry connection is now explicitly supplying its SSL context created from the in-config referenced trustStore and keyStore JKS files without relying on the automatic mechanism from the environment variables.
Tested on Menas-dev on premise where the problems manifesting with the current `develop` version, the issue seems to be resolved - a schema from the SSR can be actually loaded. Big thanks to @hamc17 who was willing to deploy the test artifacts to the environment which I do not have access to, presently.
There is a standing question if this approach, albeit usable in this case, is the general way to go for similar cases. The choice generally goes down to:
- multiple smaller key/trust stores and picking up what is needed (this PRs approach)
- having one bigger key/trust …
=> Feature/1496 SSR key/cert select

menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js, menas/ui/components/dataset/conformanceRule/FillNullsConformanceRule/add.fragment.xml, menas/ui/components/dataset/conformanceRule/FillNullsConformanceRule/display.fragment.xml
- input column now is shown in rule view
- input column pre-selected in rule edit
- general add.inputColumn now used
Fixes #1525 
RN: FillNulls conformance rule now shows an input column and when being edited the input column is preselected. 
---
**Code run and verified - @benedeki**
=> 1525 Fix FillNull Conformance Rule view

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/services/SchemaRegistryService.scala, menas/src/test/resources/application.properties, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/SchemaApiFeaturesIntegrationSuite.scala
Menas config key change:
- `menas.schemaRegistryBaseUrl` => `menas.schemaRegistry.baseUrl`
(the underlying reason is explained in the issue #1565 - to conform to other key(s) in the `menas.*` config space)
=> menas config unification

menas/ui/components/SchemaTable.js, menas/ui/components/dataset/conformanceRule/ConformanceRule.js, menas/ui/components/dataset/datasetDetail.controller.js, menas/ui/components/dataset/datasetDetail.view.xml, menas/ui/components/mappingTable/mappingTableDetail.controller.js, menas/ui/components/mappingTable/mappingTableDetail.view.xml, menas/ui/components/schema/schemaDetail.controller.js, menas/ui/components/schema/schemaDetail.view.xml, menas/ui/components/schemaTable.fragment.xml, menas/ui/css/style.css, menas/ui/generic/formatters.js
This feature allows the user to see what the conformed schema is about to look like (i.e. current schema + conformance rules applied). The result is not saved anywhere, it is in UI only.
There is an icon indication for the to-be-added fields, this also works in depth.
I haven't invented the conf rule application logic, only adjusted the front-end to view it (added one parameter to the logic to distinguish original vs added schema fields. Some other necessary adjustments had to be made to reuse the existing treatable fragment (original clashed on ids when reused).
This is what it looks like:
=> #763 conformed schema in Menas UI

spark-jobs/pom.xml
Fixes #1618 by providing a compatible commons library (v0.0.15). 
Test ran manually on EMR.
Thanks @AdrianOlosutean for the tip.
=> Fix spline 0.5.5 integration

menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
Just switch the order of update `RuleValidationsAndFields` so that the proper fields are "dominant"
Fixes #1638 
RN: Fix the validation of conformance rules on import and the evolving schema
=> 1638 Fix validation of conformance rules on import entity

data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala, data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala, data-model/src/main/scala/za/co/absa/enceladus/model/properties/propertyType/package.scala, data-model/src/test/scala/za/co/absa/enceladus/model/conformanceRule/ConformanceRuleTest.scala, menas/src/main/scala/za/co/absa/enceladus/menas/repositories/DatasetMongoRepository.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/repositories/DatasetRepositoryIntegrationSuite.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/CommonMappingRuleInterpreter.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationExecutionSuite.scala
* `overrideMappingTableOwnFilter` made optional
* added UT testing the old serialization
* fixed a few compilation warnings
Fixes #1666 
Release notes:
`overrideMappingTableOwnFilter` was made optional in `MappingConformanceRule` de-/serialization so old serializations of conformance rules without the property are still readable.
=> #1666: `overrideMappingTableOwnFilter` in `MappingConformanceRule` makes its old serialization incompatible

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/PropertyDefinitionController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/RestExceptionHandler.scala, menas/src/main/scala/za/co/absa/enceladus/menas/exceptions/EndpointDisabled.scala, menas/src/test/resources/application.properties
So I tried a few approaches. Flips library, togglz library, refresh scope, cloud starter, profiles, custom annotations/Aspect and maybe more. Not sure. Got lost. Anyway, all too big or complicated. Might be hard to remove.
Also, found out that changing values of app props on the flight is Spring anti-pattern. 
**Solution** is a "simple" property that is set at the beginning of service start, has a default of false and only enables and disables property definitions updates. Will also be quick to revert without leaving any ghost annotations or configs. 
Nagging: Would be quite easier if we already had that stand-alone Configuration object using `@ConfigurationProperties`. 
Fixes #1637 
Relase Notes: Property Definition Updates can be enabled using a switch …
=> 1637 Add simple switch for prop definitions updates

menas/ui/components/dataset/addDataset.fragment.xml, menas/ui/components/dataset/datasetInfo.fragment.xml, menas/ui/components/hdfs/HDFSBrowser.js, menas/ui/components/mappingTable/addMappingTable.fragment.xml, menas/ui/index.html, menas/ui/service/EntityDialog.js, menas/ui/service/EntityValidationService.js, menas/ui/service/HdfsService.js
HDFS Browser can now be hidden
- by a click of a button
- automatically on dialog open when one of the paths cannot be displayed in the HDFS Browser
Background:
- the HDFS listing AJAX call was originally part of the HDFS browser itself; the call routine has been extracted into a HdfsService, directly used by the HDFS Browser. 
- jQuery & ES6 Promise wrappers have been added for the HDFS listing call to enable promise composition to be used in dialogs (dataset dialog) where multiple HDFS checks are needed without custom chaining
- The dialog assembly logic has been changed for the service loading to be done first and the dialog to be shown later, otherwise the dialog elements may flicker to react to the listing changes.
- Entering HDFS/S3 paths can now be done either using the existing …
=> Hdfs browser hiding

menas/src/main/scala/za/co/absa/enceladus/menas/Application.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/LandingPageController.scala, menas/src/main/scala/za/co/absa/enceladus/menas/repositories/LandingPageStatisticsMongoRepository.scala, menas/src/main/scala/za/co/absa/enceladus/menas/utils/implicits/package.scala
Fixes #1679 
This PR proposes how such expensive queries could be addressed before we invest into the massive data model rebuild or before we got requirements with more advanced caching needs (where products like redis could be used)
Here Spring will run the recalculation of the landing page statistics upon the start up and subsequently in 15 minute intervals. These statistics are stored in a mongo collection and the API endpoint simply reads the latest record.
=> #1679 Landing page information takes a minute to load with 1.3M runs

menas/src/main/resources/application.properties.template, menas/src/main/scala/za/co/absa/enceladus/menas/MvcConfig.scala, menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala, menas/src/main/scala/za/co/absa/enceladus/menas/auth/AuthConstants.scala, menas/src/main/scala/za/co/absa/enceladus/menas/auth/InMemoryMenasAuthentication.scala, menas/src/main/scala/za/co/absa/enceladus/menas/auth/MenasAuthenticationSuccessHandler.scala, menas/src/main/scala/za/co/absa/enceladus/menas/auth/jwt/JwtAuthenticationFilter.scala, menas/src/main/scala/za/co/absa/enceladus/menas/auth/kerberos/MenasKerberosAuthentication.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/PropertyDefinitionController.scala, menas/src/test/resources/application.properties, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/BaseRestApiTest.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/PropertyDefinitionApiIntegrationSuite.scala
Fixes #1669 
RN: 
- Add configuration property `menas.auth.admin.role` to specify an admin role to operate property definitions create and update operations. 
- Remove temporary `menas.feature.property.definitions.allowUpdate` configuration property.
- Fix JWT not holding any roles/authorities
- Add the ability to filter the roles that are going to be used in JWT token and filtration by regex. This regex can be specified in the configuration property  `menas.auth.roles.regex`.
=> 1669 Add Admin Role based authorization for property def

plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaSecurityParams.scala, plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginImpl.scala, plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/kafka/KafkaPluginSuite.scala, spark-jobs/src/main/resources/reference.conf
As the issue specifies, the following settings are needed for SSL secured Kafka topic to be produced messages to. Those can be applied either by updating the `spark-jobs`' `application.conf` or via the `--conf "spark.driver.extraJavaOptions=-Dconfig.key.here=config.value.here` method.
```
standardization.plugin.postprocessor.1=za.co.absa.enceladus.plugins.builtin.errorsender.mq.kafka.KafkaErrorSenderPlugin
conformance.plugin.postprocessor.1=za.co.absa.enceladus.plugins.builtin.errorsender.mq.kafka.KafkaErrorSenderPlugin
kafka.error.client.id="my-error-client-id1"
kafka.error.topic.name="example.error.publishing.topic"
kafka.schema.registry.url:"https://my1017.schema.registry.example.com:8081"
kafka.bootstrap.servers="my1013.bootstrap.server.example.com:9094,my1014.bootstrap.server.example. …
```
=> Sending errors to a secured kafka

scripts/bash/run_enceladus.sh, scripts/cmd/_run_enceladus.cmd
* Added `-e` switch to `klist` call in helper scripts
* Menas keytab authentication has been implemented for Windows helper script
Release note:
Keytab authentication now supported by Windows _Helper Scripts_ too. General better keytab logging in _Helper Scripts_ (`klist -e`).
Closes #1718
=> #1718: Show keytab entry key type in helper scripts

plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala, utils/src/main/scala/za/co/absa/enceladus/utils/modules/SourcePhase.scala
For some reason, this test result was previously not correctly checked (only manifested with error log but did not break the test as expected).
Now, this PR fixes the test in terms of string capitalization - while leaving the production code intact.
- No testing needed - CI build is done automatically and it has been passing.
RN suggestion
`KafkaErrorSenderPluginSuite` test fix for `SourcePhase.{Standardization, Conformance}` capitalization.
=> 1774 kafka error test fix (SourcePhase capitalization)

data-model/src/main/scala/za/co/absa/enceladus/model/properties/propertyType/package.scala, data-model/src/test/scala/za/co/absa/enceladus/model/PropertyDefinitionTest.scala, data-model/src/test/scala/za/co/absa/enceladus/model/properties/propertyType/PropertyTypeTest.scala, menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala, menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/PropertyDefinitionApiIntegrationSuite.scala, menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala, menas/ui/components/app.controller.js, menas/ui/components/dataset/addDataset.fragment.xml, menas/ui/components/login/loginDetail.controller.js, menas/ui/generic/functions.js, menas/ui/service/EntityDialog.js, menas/ui/service/EntityService.js, menas/ui/service/EntityValidationService.js
#1789 backport to 2.20.1
My own naive UI testing worked:
- edited an existing dataset to contain properties, again editing them - unsetting some of the properties. Correctly show in UI and expected properties maps also existed in the Mongo DB
- created a new DS with some non-mandatory properties not set, mongo DB collection contained the expected map.
=> Hotfix: suggestedValueNotApplied for 2.20.1 #1796

dao/src/main/scala/za/co/absa/enceladus/dao/MenasDAO.scala, dao/src/main/scala/za/co/absa/enceladus/dao/rest/MenasRestDAO.scala, dao/src/test/scala/za/co/absa/enceladus/dao/rest/MenasRestDAOSuite.scala, menas/src/main/scala/za/co/absa/enceladus/menas/controllers/DatasetController.scala, utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala, utils/src/test/scala/za/co/absa/enceladus/utils/validation/ValidationLevelSuite.scala
* defined `DefaultValidationLevel`
* default value for `validationLevel` in `getDataset`
* if value for validationLevel is equal to DefaultValidationLevel, validation level is not added to query string
Release notes:
MenasDAO.getDataset made backward compatible.
Closes #1787
=> #1787: MenasDAO.getDataset backwards compatibility fix

menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala
Allowing the path for cRonstrue to be loaded without authorization seems to be needed to get correct Menas behavior without having to refresh the page after login.
- naively test ran on my machine: even on login page, the library is now loaded immediately:
Also, having an existing custom dataset with defined schedule and having oozie enabled in config (so that the Scheduling tab is reachable), now the dataset data and its scheduling details are also correctly shown in the UI (this was not the case for the first run after login before this fix)
hints: of course, we should remerge/cherrypick this to other branches (`hotfix/2.{20,21}.1`, `develop`, ...)
=> cronstrue not being loaded without existing session

menas/pom.xml
For `menas`, the existing licence check ignore items (particular for `menas`) are moved to the `license-check` profile to align the with the `root.pom` (and actually not to prevent otherwise successful build)
- the `<exclude>ui/dist/**</exclude>` entry is added for convenience when license-checking on a built codebase.
=> rat-plugin config for menas in a profile (same as root pom.xml)

menas/ui/service/EntityService.js
This PR addresses 2 problems: 
1. when updating a dataset (using _Edit_), new ds property values are in `_properties` (while the old values are in `properties`); while for conformance rules update, the values are only in `properties`, as they are not being changed. (so, `_properties` is not defined)
2. when changing CRs, the ds properties are not kept (they get stripped) - update/delete/move (therefore simple `if(!dataset._properties) {...}` does not suffice)
The code now works as follows: only `_properties` are being blank-checked-and-fixed (moved to `DatasetService.cleanupEntity`), while for CR updates, the `properties` are used.
Note to self: we are so missing an UI testing framework being employed :(
- on localhost:
1. create a dataset with ds properties -> checked in UI and DB for …
=> strip blank properties fix

menas/ui/service/EntityService.js
_This PR is a backport of #1824 for version 2.22._
This PR addresses 2 problems: 
1. when updating a dataset (using _Edit_), new ds property values are in `_properties` (while the old values are in `properties`); while for conformance rules update, the values are only in `properties`, as they are not being changed. (so, `_properties` is not defined)
2. when changing CRs, the ds properties are not kept (they get stripped) - update/delete/move (therefore simple `if(!dataset._properties) {...}` does not suffice)
The code now works as follows: only `_properties` are being blank-checked-and-fixed (moved to `DatasetService.cleanupEntity`), while for CR updates, the `properties` are used.
Note to self: we are so missing a UI testing framework being employed :(
- on localhost:
1. create a dataset …
=> strip blank properties fix for 2.22

menas/ui/service/EntityService.js
_This PR is a backport of #1824 for version 2.20._
This PR addresses 2 problems: 
1. when updating a dataset (using _Edit_), new ds property values are in `_properties` (while the old values are in `properties`); while for conformance rules update, the values are only in `properties`, as they are not being changed. (so, `_properties` is not defined)
2. when changing CRs, the ds properties are not kept (they get stripped) - update/delete/move (therefore simple `if(!dataset._properties) {...}` does not suffice)
The code now works as follows: only `_properties` are being blank-checked-and-fixed (moved to `DatasetService.cleanupEntity`), while for CR updates, the `properties` are used.
Note to self: we are so missing a UI testing framework being employed :(
- on localhost:
1. create a dataset …
=> strip blank properties fix backport to 2.20

data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala, data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala, data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala
**How it looks now:**
**Release notes**: 
Now Audit Trail in Menas shows added, removed and changed properties
Fixes #1820
=> 1820 Fix auditable message for Dataset Properties

menas/ui/service/EntityService.js
_This PR is a backport of #1824 for version 2.21._
This PR addresses 2 problems: 
1. when updating a dataset (using _Edit_), new ds property values are in `_properties` (while the old values are in `properties`); while for conformance rules update, the values are only in `properties`, as they are not being changed. (so, `_properties` is not defined)
2. when changing CRs, the ds properties are not kept (they get stripped) - update/delete/move (therefore simple `if(!dataset._properties) {...}` does not suffice)
The code now works as follows: only `_properties` are being blank-checked-and-fixed (moved to `DatasetService.cleanupEntity`), while for CR updates, the `properties` are used.
Note to self: we are so missing a UI testing framework being employed :(
- on localhost:
1. create a dataset …
=> strip blank properties fix for 2.21

spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
* Timezone in metadata is taken into account even if the source is already timestamp or date
Release note:
Time zone in metadata is taken into account even if the source data is already of timestamp type.
=> #1836: Standardization ignores timezone metadata for timestamp type in case the source is already timestamp

spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
* Timezone in metadata is taken into account even if the source is already timestamp or date
=> #1836: Standardization ignores timezone metadata for timestamp type in case the source is already timestamp (2.21)

spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala
SparkVersionGuard: For Spark 3, the min version has been set to 3.0.0
Closes #1808.
=> #1808SparkVersionGuard: For Spark 3, min version = 3.0.0

menas/ui/service/EntityDialog.js, menas/ui/service/EntityValidationService.js
* Show dialogs only on submit not in case of validation on the fly
* Show property warning only if all Mandatory has passed validation
Release notes:
When saving a dataset with undefined recommended property a warning dialog is shown
=> #1844: When saving a dataset with undefined recommended property show a warning dialog (2.21)

menas/ui/components/dataset/addDataset.fragment.xml, menas/ui/css/style.css
As outlined in #1842, a longer dataset property name may have previously been cut off and the user was unable to reach the whole string.
The dialog has undergone several changes to address the problem at hand, namely:
- width of the value field has been slightly decreased (the values from the selection will be fully visible when opened if smaller)
- default width of the dialog has been set to 55em (sufficient in testing), but mainly, the dialog has been made stretchable -- so if the user wants to enlarge the dialog to have more space, they can
- more sensible tooltip has been provided - revealing the full property name string and optionally the description if available -- thus, the user can read a very long property name this way, too, if ellipsized
(I have also attempted to diminish the …
=> 1842 Dataset Dialog - properties editing update

menas/ui/components/dataset/addDataset.fragment.xml, menas/ui/css/style.css
_This is the same as https://github.com/AbsaOSS/enceladus/pull/1845 for Enceladus 2.22.2_
- as stated in https://github.com/AbsaOSS/enceladus/pull/1845, Dataset edit dialog has been updated:
- layout tweaked, resizable (default: Small), enhanced tooltips, properties border 
I have test-ran it on local Menas and noticed no change from the original in #1845.
Relates to #1842.
=> 1842 Dataset Dialog - properties editing update for 2.22

plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/InfoProducerKafka.scala, plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaConnectionParams.scala, plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaSecurityParams.scala, plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/SchemaRegistrySecurityParams.scala, plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/kafka/KafkaPluginSuite.scala, plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala, spark-jobs/src/main/resources/reference.conf, spark-jobs/src/main/scala/za/co/absa/enceladus/common/Constants.scala
New configs for SparkJobs using kafak plugins
- kafka.schema.registry.basic.auth.credentials.source
- kafka.schema.registry.basic.auth.user.info
Release Notes:
Added new properties for KafkaPlugins to be able to connect to Secured SchemaRegistry
Fixes #1807
=> 1807 Add schema registry security params

menas/ui/components/login/loginDetail.controller.js
Just a simple removal of a dialog popping up, if conditions are met on Menas opening.
_Release notes suggestion:_
Warning of non-Chrome browsers reworked and reworded. Multiple other browsers should work now without warning: Firefox 78+, Edge 79+, Safari 12+.
=> #1853: Remove the warning of wrong browser type and version in Menas

spark-jobs/src/main/resources/reference.conf, spark-jobs/src/main/scala/za/co/absa/enceladus/common/ErrorColNormalization.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformancePropertiesProvider.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/FeatureSwitches.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala, spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/simpleMultiOutSchema.txt, spark-jobs/src/test/scala/za/co/absa/enceladus/common/error/ErrorMessageFactory.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/fixtures/StreamingFixture.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingGroupExplodeSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingInterpreterSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleBroadcastSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/NestedTestCaseFactory.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StdInterpreterSuite.scala, utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala, utils/src/main/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicits.scala, utils/src/test/scala/za/co/absa/enceladus/utils/ExplosionSuite.scala, utils/src/test/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicitsSuite.scala
The problem is at length described in https://github.com/AbsaOSS/enceladus/issues/1818, but to sum up:
When running conformance under Spark 3.1, the `errCol` is not nullable; while it is nullable under Spark 2.4
[utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala](https://github.com/AbsaOSS/enceladus/blob/cbc06ff3b329b6f5eb169b499a65b4d36f567ce4/utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala#L184) calls 
```scala
decDf.orderBy(orderByRecordCol, orderByInsideArray)
.groupBy(groupByColumns: _*)
.agg(collect_list(deconstructedField).as(tmpColName),
array_distinct(flatten(collect_list(col(errorCol)))).as(errorCol))
```
On Spark 3, the `errCol` in `decDf` is nullable, while in the result of this operation, `errCol` is not nullable anymore. …
=> #1818 errCol added in Conformance is not Nullable

.editorconfig, .gitattributes, scripts/cmd/_enceladus_env.template.cmd, scripts/cmd/_run_enceladus.cmd
* added configuration for date parsing type
* .gitattributes changed to hopefully better handle CRLF in native Windows files
* LF -> CRLF in *.cmd and *.bat files
I needed to implement the partial changes for my testing for other issues. So I thought to make it more general and include in code-base.
_Release notes:_
Configuration of the date parsing (locale dependent) to correctly name the log file.
=> #1835: Support multiple date formats in Helper scripts

_config.yml, _docs/2.0.0/usage/schema.md
* changed markdown parser configuration
* removed extra _ around timestamp patterns of type epoch
=> #1870: Typographic typos in documentation

pom.xml
To suppress this _warning_ during compilation:
```
Warning:java: source value 1.5 is obsolete and will be removed in a future release
Warning:java: target value 1.5 is obsolete and will be removed in a future release
```
=> Suppress compiler warning of obsolete Java

menas/ui/components/dataset/conformanceRule/RuleColumnDialog.js
Fixes #1909 
Release Notes: Increased limit of columns shown in the selector for Coalesce and Concatenation conformance rules to 5000. This should fit most needs.
=> #1909 Increase the limit of columns shown in menas column selection

utils/src/main/scala/za/co/absa/enceladus/utils/types/DefaultsByFormat.scala, utils/src/test/resources/application.conf, utils/src/test/scala/za/co/absa/enceladus/utils/types/DefaultsByFormatSuite.scala
* rename of the configuration prefix from `enceladus.` to `standardization.`
Just a little change in the new configuration name. Believe it doesn't need retesting, that the UTs are enough.
=> #1887 defaultTimestampTimeZone can be source type specific

spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/StandardizationAndConformanceJob.scala
* added unpersist after Standardization in` StandardizationAndConformanceJob.scala`
Closes #1968 
Release notes:
Releasing cached standardization data after its phase in the combined _Standardization&Conformance job_, reducing its memory requirement.
=> #1968: Release standardized dataframe after its saving in the combined

menas/ui/components/mappingTable/filterEdit/filterTreeEdit.fragment.xml, menas/ui/service/FilterTreeUtils.js
This PR solves the icons mixup for filter editing mentioned in #1978 :
(⬆️ shows the mixed-up state prior to this PR)
Now, the icons are as intended and also conform to the icons used in filter view.
Filter editing now:
Filter view (unchanged, just for reference):
Closes #1978 
Filter edit icons are now switched to better convey their expected meaning and to conform to the icons used in the filter view.
=> #1978 icons mixup corrected for filter edit

menas/ui/components/dataset/conformanceRule/MappingConformanceRule/display.fragment.xml
As outlined in issue #1981 description, a Mapping Conformance Rule title (with rule index) was missing in the _Conformance Rules view_. This PR aims to solve the issue and also adds the missing _Check Control Measures_ checkbox view (that was incidentally found missing, too).
The issue was most probably introduced in https://github.com/AbsaOSS/enceladus/pull/1721/files#L21 - where for the MCR, a functionality for multiple outputs was added.
It was correctly identified then that the original fragment (containing an indexed label, control measures checkbox, and single output view) was not usable anymore, because it forces single column output (the MCR view accounts displaying the output columns) - **so the fragment usage was removed, however, no suitable replacement was given - leaving the …
=> #1981 MCR title missing bugfix

.gitignore, spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
* Handling 0 partition case in repartitioning
* .gitignore duplicate entry fixed
_Release notes:_
_Fixed issue when trying to repartition an empty dataset with 0 partitions._
=> #1987: Repartitioning prevents processing of zero size files - ver. 2.25

menas/pom.xml, pom.xml, spark-jobs/pom.xml
* Menas gets log4j via Spring, explicitly imported to ensure 2.15 is used
* Upgraded Hyperdrive in SparkJobs which already uses log4j 2.15
Fixes #1998
=> #1998: Ensure log4j v2 at least 2.15.0

_data/menas-configuration_2_0_0.yml
Multi-AD documentation added to GH pages.
(`menas.auth.ad.server=ldaps://first.ldap.here ldaps://second.ldap.here ldaps://third.ldap.here`)
=> #2024 multiple AD - GHP doc

menas/src/main/resources/application.properties.template
Multiple AD option outlined in Menas' `applictation.properties` template.
Btw. I also have a strong suspicion that the sibling config option `menas.auth.ad.domain` is completely useless.
=> #2024 multiple AD - Menas' application.properties.template

utils/src/test/scala/za/co/absa/enceladus/utils/config/SecureConfigSuite.scala
Let's see the SonarCube check pass for the password-in-code.
Fixes #2040
=> #2040 attempting not to trigger sonarcube password-in-code in tests

database/src/main/dataset/_.ddl, database/src/main/dataset/_add.sql, database/src/main/dataset/add.sql, database/src/main/dataset/entities.ddl, database/src/main/dataset/get.sql, database/src/main/dataset/list.sql, database/src/main/dataset/versions.ddl, database/src/main/mapping_table/entities.ddl
* tables to store the dataset entities
* basic function to work with dataset entities
Closes #2035
=> #2035: PG data model and functions for Dataset

menas/ui/components/home/landingPage.view.xml
As requested in #2095, the order of the buttons on the lading page has been changed as follows:
1. Runs
2. Schemas
3. Datasets
4. Mapping Tables
5. Dataset Properties
Closes #2095,
Menas UI: Lading page buttons order has been changed to conform the order of items in the left-side menu.
=> #2095 Menas UI: landing page button order changed

examples/src/test/resources/log4j.properties, pom.xml, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/OptimizerTimeTracker.scala, spark-jobs/src/test/resources/log4j.properties, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/CastingRuleSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingGroupExplodeSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleBroadcastSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationRerunSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/CounterPartySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_BinarySuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DateSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DecimalSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_FractionalSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_IntegralSuite.scala, spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_TimestampSuite.scala, utils/pom.xml, utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/TZNormalizedSparkTestBase.scala, utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala, utils/src/test/scala/za/co/absa/enceladus/utils/broadcast/LocalMappingTableSuite.scala
* integration of Spark-commons and Spark-commons-test 0.3.1
* function `cache` replaced with `cacheIfNotCahcedyet`
* removed filter for test logs of `DataFrame already being cached
* `TZNormalizedSparkTestBase` take into account eventual timezone config
Closes #2090
=> #2090: Integrate Spark-Commons 0.3.x

README.md, rest-api/src/main/scala/za/co/absa/enceladus/rest_api/SpringFoxConfig.scala
Swagger doc fix:
- runs V3 were missing from the swagger UI
- Brief API description in README has been updated.
#2092 
- Swagger doc for API V3 Runs added.
=> #2092 swagger doc: fix for runs + readme description enhanced

_data/configuration_3_0_0.yml, _docs/3.0.0/usage/run.md
[#2105] Documentation (3.0.0) of spark-jobs that described `menas.rest`-prefixed confs has been updated as these now describe `enceladus.rest`-prefixed confs.
=> #2105 Change `menas.rest` to `enceladus.rest` in Github Pages

data-model/src/main/scala/za/co/absa/enceladus/model/dataFrameFilter/package.scala, data-model/src/test/scala/za/co/absa/enceladus/model/dataFrameFilter/DataFrameFilterSuite.scala
Changed set `&` to `union` in `and` and `or` functions in case two `AND`/`OR` filters are joined.
Fixes #2112
=> #2112 Fix `and` and `or` functions in DataFrameFilter

README.md, examples/data/e2e_tests/test_jsons/castingConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/coalesceConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/concatenationConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/literalConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/mappingConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/negationConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/singleColumnConformanceRuleTest.json, examples/data/e2e_tests/test_jsons/stdNfDnTest.json, examples/data/e2e_tests/test_jsons/stdNfDyTest.json, examples/data/e2e_tests/test_jsons/stdNtDnTest.json, examples/data/e2e_tests/test_jsons/stdNtDyTest.json, examples/data/e2e_tests/test_jsons/uppercaseConformanceRuleTest.json, examples/src/main/resources/application.conf.template, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala, examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala, examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/XPadCustomConformanceRuleSuite.scala, rest-api/src/main/resources/scheduling/oozie/workflow_template.xml, spark-jobs/src/main/resources/reference.conf, spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala, spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformanceAttributes.scala, spark-jobs/src/test/resources/application.conf
As requested in #2105, configuration keys (spark-jobs) with prefix `menas.rest` have been changed to have prefix `enceladus.rest` instead.
Note: this PR only changes these configurations, code refactoring to remove other mentions of Menas when REST API is intended should also be covered, in another issue/PR.
spark-jobs: Configuration keys starting with `menas.rest` were changed to `enceladus.rest`.
=> #2105 Change spark-jobs config keys prefix from `menas.rest` to `enceladus.rest`

dao/src/main/scala/za/co/absa/enceladus/dao/rest/CrossHostApiCaller.scala, dao/src/test/scala/za/co/absa/enceladus/dao/rest/CrossHostApiCallerSuite.scala, dao/src/test/scala/za/co/absa/enceladus/dao/rest/RestDaoFactorySuite.scala
- Added `retryBackoffStrategy` parameter to CrossHostApiCaller constructor
- Used `retryBackoffStrategy` as a step in retrying a call
- Implemented quadratic `retryBackoffStrategy` with randomised addition of 0-1s to delay
Closes #2121
=> #2121 Implement retries quadratic+randomised backoff mechanism

dao/pom.xml, dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala, data-model/pom.xml, data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala, data-model/src/main/scala/za/co/absa/enceladus/model/Exportable.scala, data-model/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala, data-model/src/main/scala/za/co/absa/enceladus/model/Schema.scala, data-model/src/main/scala/za/co/absa/enceladus/model/properties/PropertyDefinition.scala, data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/DatasetFactory.scala, data-model/src/test/scala/za/co/absa/enceladus/model/conformanceRule/ConformanceRuleTest.scala, migrations/pom.xml, pom.xml, rest-api/pom.xml
This PR increases the version of the Atum library to v3.9.0. (internally, that solves a couple of CVEs - details: https://github.com/AbsaOSS/atum/issues/150)
Test-ran on localhost, `_INFO` files appearing correctly both in std and conf outputs as expected.
Closes #2154.
=> #2154 CVE fix: Atum updated to v3.9.0

dao/pom.xml, data-model/pom.xml, data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala, data-model/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala, data-model/src/main/scala/za/co/absa/enceladus/model/backend/Reference.scala, data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala, menas/pom.xml, migrations-cli/pom.xml, migrations/pom.xml, plugins-api/pom.xml, plugins-builtin/pom.xml, pom.xml, rest-api/pom.xml, spark-jobs/pom.xml, utils/pom.xml
Closes #2180 
Multiline annotations squashed to single line.
Version reverted to 3.0.0-SNAPSHOT (as 3.0.0 was not yet released due to this error)
After this is merged, I intend to remove the v3.0.0 tag from where it is currently put
=> #2180 multiline annotations squashed to single line.

dao/pom.xml, dao/src/main/scala/za/co/absa/enceladus/dao/rest/RestClient.scala, data-model/pom.xml, menas/pom.xml, migrations-cli/pom.xml, migrations/pom.xml, plugins-api/pom.xml, plugins-builtin/pom.xml, pom.xml, rest-api/pom.xml, spark-jobs/pom.xml, utils/pom.xml
Closes #2182 
An "unmoored" doc addressed - my understanding is that the issue is a local method being java/scala-documented.
Version reversed to 3.0.0-SNAPSHOT
=> #2182 fixing unmoored doc, reverting to 3.0.0-SNAPSHOT
