AbsaOSS/enceladus

- menas/ui/components/app.view.xml
- menas/ui/components/dataset/datasetMain.view.xml
- menas/ui/components/mappingTable/mappingTableMain.view.xml
- menas/ui/components/schema/schemaMain.view.xml
I have added (extended) IDs for menus and tab menus
> Add ids to elements in side menu and each components tab menu

- Jenkinsfile
Creates a basic Jenkins file with build job on it.
> Add basic build jenkinsfile

- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/BaseController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/HDFSController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/MappingTableController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/RestExceptionHandler.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/SchemaController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/SparkController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/UserInfoController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/controllers/VersionedModelController.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/exceptions/EntityInUseException.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/exceptions/NotFoundException.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/exceptions/ValidationException.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/models/Validation.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/repositories/MongoRepository.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/repositories/VersionedMongoRepository.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/DatasetService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/HDFSService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/MappingTableService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/ModelService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/SchemaService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/VersionedModelService.scala
- menas/src/test/scala/za/co/absa/enceladus/rest/services/HDFSServiceSuite.scala
- menas/src/test/scala/za/co/absa/enceladus/rest/services/MappingTableServiceTest.scala
- menas/src/test/scala/za/co/absa/enceladus/rest/services/SchemaServiceTest.scala
- menas/src/test/scala/za/co/absa/enceladus/rest/services/VersionedModelServiceTest.scala
- menas/ui/components/schema/schemaMain.controller.js
- menas/ui/service/DatasetService.js
- menas/ui/service/GenericService.js
- menas/ui/service/MappingTableService.js
- menas/ui/service/SchemaService.js
First step to making things a bit more properly RESTful. Not perfect, but let's get going.
> Add appropriate HTTP response codes

- menas/src/main/scala/za/co/absa/enceladus/rest/WebSecurityConfig.scala
- menas/ui/components/Component.js
- menas/ui/components/app.controller.js
- menas/ui/components/dataset/datasetMain.controller.js
- menas/ui/components/login/loginMain.controller.js
- menas/ui/components/login/loginMain.view.xml
- menas/ui/components/mappingTable/mappingTableMain.controller.js
- menas/ui/components/schema/schemaMain.controller.js
- menas/ui/generic/functions.js
- menas/ui/index.html
- menas/ui/service/GenericService.js
- Login/Logout are now restful.
- Simple login page inside the sapUI5 front-end, with routing that leads to the login page if you're unauthenticated and doesn't allow you to go back to it if you are.
- Supports multiple tabs being open, session lives on until it expires or user logs out.
- If user has two tabs open and logs out from one, when they try to do anything on the other they are sent to log in.
> 104 Add login page

- CONTRIBUTING.md
Thanks to @Zejnilovic for the initial template for this!
> 118 Add CONTRIBUTING.md

- README.md
Just an initial README, barebones. Focus should be on making it clear how to build and run. We will provide more extensive documentation whit first release in Project Pages and Wiki.
> 109 Add README.md

- pom.xml
- scalastyle-config.xml
Open to suggestions on specifics.
> 99 Set up preliminary scalastyle

- dataModel/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/RestService.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/DatasetService.scala
- menas/ui/components/dataset/datasetMain.controller.js
- menas/ui/service/DatasetService.js
- menas/ui/service/RuleService.js
- Concept used for implementation: Any change related to Dataset should be done via update Dataset endpoint.
- Implemented without validation. It will be implemented in separate future. 
- Warning fixes.
**1. Run tests:**
- go to enceladus dir
- mvn -DskipTests clean package
- mvn verify
- **Expected result**: All tests should pass
**2. Remove rule:**
- Run application
- Log in 
- Go to Dataset tab 
- Pick one of the datasets (or Create new dataset)
- Go to Conformance Rules
- Create at least 2 rules 
- Delete one of them 
- **Expected result**: Rule should be removed. Dataset version should be increased.
> #84 Delete conformance rule

- pom.xml
- scalatest to 3.0.5
- scalatest-maven-plugin to 2.0.0
This speeds up the build thanks to performance improvements in the libraries.
> Update scalatest and scalatest-maven-plugin versions

- menas/src/main/scala/za/co/absa/enceladus/rest/utils/converters/SparkMenasSchemaConvertor.scala
- menas/src/test/scala/za/co/absa/enceladus/rest/utils/converters/SparkMenasSchemaConvertorSuite.scala
This passes the fixed unit tests, which covers all of the possible cases.
> #228 Fix nested arrays conversion from menas schema type to Spark Struct

- menas/ui/service/DatasetService.js
- menas/ui/service/MappingTableService.js
- menas/ui/service/SchemaService.js
If no entities are retrieved, ensure to clear the current entity
model path.
> #27 Old data lingers even if all items in view are deleted

- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
* Fixing old function name leftover from an earlier refactor, that prevented build
* Adhering to scalastyle
> #156: Configuration of service time zone

- utils/src/test/scala/za/co/absa/enceladus/utils/types/EnceladusDateParserSuite.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorsSuite.scala
* Added unit tests showing and verifying the existing classes already support offset timezone
> #157: Add support for offset time zone notation in timestamp format

- menas/ui/index.html
> #195 Fix hamburger menu

- Jenkinsfile
Added in a call to groovy script to publish over SSH to CD instance.
> #284: Updated Jenkinsfile for CD

- dataModel/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
- dataModel/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala
- dataModel/src/main/scala/za/co/absa/enceladus/model/Schema.scala
- menas/src/main/scala/za/co/absa/enceladus/rest/services/DatasetService.scala
Changing the default version of all menas entities from 0 to 1
> #164 Consistent Dataset Versioning

- Jenkinsfile
On a merge with these changes the groovyUtils repo update will be merged
> 325 Changed calls to Nexus to call Artifactory

- menas/ui/components/dataset/addDataset.fragment.xml
- menas/ui/components/dataset/addDataset.js
- menas/ui/components/hdfs/HDFSBrowser.js
- menas/ui/components/hdfs/HDFSBrowserRenderer.js
- menas/ui/components/mappingTable/addMappingTable.fragment.xml
- menas/ui/components/mappingTable/addMappingTable.js
- menas/ui/service/EntityValidationService.js
- Changed Text to Input component for manual entry
- Added better validation directly to the HDFS browser
- Changed valueState to Warning for invalid HDFS paths
> 169 Editing dataset with wrong paths in HDFS makes user change the path to root first

- utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala
> #329 Fix array reordering in the experimental mapping rule implementation

- menas/ui/components/dataset/addDataset.fragment.xml
- menas/ui/components/hdfs/HDFSBrowser.js
- menas/ui/components/mappingTable/addMappingTable.fragment.xml
> #333 Switch the order of input field with HDFS Browser component

- menas/ui/components/login/loginMain.controller.js
- menas/ui/components/login/loginMain.view.xml
The binding initialisation with "" overwrote autocomplete
> #245 Login form doesn't work with form autocomplete

- menas/ui/components/dataset/conformanceRule/upsert.controller.js
- menas/ui/components/mappingTable/mappingTableDetail.controller.js
- menas/ui/components/schemaFieldSelector.fragment.xml
- menas/ui/index.html
- menas/ui/service/EntityService.js
- menas/ui/service/SchemaFieldSelector.js
This should also address #364 and #363.
This is a very ugly refactoring of some pretty involved bits of JS. I don't really want to give it a rewrite, I hope just abstracting it out of the controllers and reducing the duplication is enough for now.
> #393 Extract SchemaFieldSelector component

- menas/src/main/scala/za/co/absa/enceladus/menas/services/HDFSService.scala
HDFS Browser explodes when the user running menas doesn't have execute permission on one of the subfolders. This is due to the fact that we need to indicate whether it's empty or not (display the expansion arrow or not).
> #399 HDFS Browser fails to retrieve folder listing

- testutils/pom.xml
- testutils/src/main/scala/za/co/absa/enceladus/testutils/exceptions/CompareJobExceptions.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/exceptions/InfoFileComparisonExceptions.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/infoFileComparison/AtumModelUtils.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/infoFileComparison/CmdConfig.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/infoFileComparison/InfoFileComparisonJob.scala
For its heavy dependence on the Atum models, I am quite unsure if we should have it here or in Atum.
> #348 Implement _INFO file comparison

- menas/pom.xml
- pom.xml
Also added our own repo to maintain UI5 webjars versions for
finer grained control.
> #404 Upgrade version of UI5 to 1.65.1

- pom.xml
This is the fix for control values provided by Source and Raw metrics
> #415 Fix source and raw checkpoint measurements serialization

- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/ConcatenationColumnDialog.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/ConcatenationColumnDialog.js
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/ConcatenationColumnDialogFactory.js
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/add.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConformanceRuleDialog.js
- menas/ui/components/dataset/conformanceRule/schemaManager.js
- menas/ui/components/mappingTable/mappingTableDetail.controller.js
- menas/ui/index.html
- menas/ui/service/SchemaFieldSelector.js
* Fixed broken concatenation output nullability check
* Added Schema Field Selector
> #339 Add schema selector for concatenation rule

- menas/ui/components/app.controller.js
- menas/ui/components/login/loginDetail.controller.js
This PR adds a warning if user is using anything other than:
Chrome version >= 68
> #456 Check for supported browsers

- conformance/src/main/resources/application.conf.template
- conformance/src/main/scala/za/co/absa/enceladus/conformance/CmdConfig.scala
- conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
This is a tiny thing to make experimental mapping rule configurable so we can turn it on by default on test environments.
> #445 Make default value for using the experimental mapping rule

- menas/ui/components/dataset/datasetDetail.controller.js
Fix for oversight in previous PR.
> #81 Reenable rule deletion, which was mistakenly left disabled

- .gitignore
- README.md
- menas/pom.xml
- menas/src/main/resources/application.properties.template
- menas/ui/Gruntfile.js
- menas/ui/index.html
- menas/ui/package-lock.json
- menas/ui/package.json
- pom.xml
- Added a profile "generateComponentPreload" which generates
a preload file from components
- Added a default cache time for static resources in spring
- Added library preload for sap.ui.table and sap.ui.layout
- Additional speed up can be achieved by enabling HTTP
compression on the server.
See KB16333: How to enable HTTP compression under Apache Tomcat
in MicroStrategy Web Universal
https://community.microstrategy.com/s/article/KB16333-How-to-enable-HTTP-compression-under-Apache-Tomcat-in?language=en_US
> #478 Speed up loading of menas

- menas/pom.xml
- pom.xml
Added the dependency which seems to be missing based on the logs
> #485 HDFS becomes inaccessible from Menas after some time

- menas/ui/components/schema/schemaDetail.controller.js
> #187 File path to previously uploaded schema lingers

- menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/repositories/OozieRepository.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/OozieService.scala
- menas/ui/components/app.controller.js
> #482 Oozie Repository validate props always returns true

- menas/ui/components/login/loginDetail.controller.js
> #198 Clear password from Menas login form after login

- menas/ui/components/schema/schemaDetail.controller.js
> #247 Upload New Schema with expired session doesn't send to login

- menas/ui/components/login/loginDetail.controller.js
> #406 Pressing back after login breaks the UI

- menas/ui/components/SchemaTable.js
- menas/ui/components/schemaTable.fragment.xml
> #185 Metadata show button in Schema fields is un-intuitive

- dataModel/src/main/scala/za/co/absa/enceladus/model/menas/scheduler/dataFormats/package.scala
- menas/ui/generic/model.js
> #439 Add JSON Format support into menas scheduling

- dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusRestDAO.scala
- this was an error during PR refactoring...
> #509 Enceladus DAO creds auth broken

- menas/ui/npm-shrinkwrap.json
- menas/ui/package.json
- here npm-shrinkwrap replaces package-lock.json
> #515 Resolve security alerts in npm

- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/ConcatenationColumnDialog.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/ConcatenationColumnDialog.js
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/add.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConformanceRule.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleDialog.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleFormFactory.js
- menas/ui/components/dataset/conformanceRule/MappingConformanceRule/JoinConditionDialog.js
- menas/ui/components/dataset/conformanceRule/MappingConformanceRule/joinConditions.fragment.xml
- menas/ui/components/dataset/conformanceRule/SchemaManager.js
- menas/ui/components/dataset/conformanceRule/upsert.fragment.xml
- menas/ui/components/dataset/datasetDetail.controller.js
- menas/ui/index.html
- menas/ui/service/GenericService.js
- menas/ui/service/RuleService.js
- menas/ui/service/SchemaFieldSelector.js
- menas/ui/service/ValidationResult.js
Validates:
* all required fields in the conformance rule forms
* minimum of 2 columns for concatenation
* concatenation column dialog
* minimum of 1 join condition for mapping
* join condition dialog
* output column that might override (of if inserting a rule in the middle of the list, be overridden by another rule later on)
* drop only columns which do not break the transitive schema (if adding a drop rule in the middle of the list)
> #83 Add Conformance Rule dialog validation

- menas/pom.xml
- menas/src/main/scala/za/co/absa/enceladus/menas/controllers/SchemaController.scala
- menas/ui/components/schema/schemaDetail.controller.js
- menas/ui/components/schema/schemaDetail.view.xml
This allows the user to upload schema either as a Spark
StructType (default) or as a cobol copybook.
> #517 Support cobol copybooks in menas

- menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js
> #425 Char is not a supported Spark type

- menas/ui/service/RunService.js
- standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
> #537 Wording consistency for Atum checkpoints

- menas/ui/service/GenericService.js
> #249 Session expired pop-up too short

- menas/ui/service/GenericService.js
> #248 Log out button doesn't work if session is expired

- menas/ui/components/app.controller.js
- menas/ui/components/dataset/datasetDetail.controller.js
- menas/ui/components/i18n/message.properties
- menas/ui/components/tables/TableUtils.js
- menas/ui/components/tables/groupDialog.fragment.xml
- menas/ui/components/tables/sortDialog.fragment.xml
- For testing, implemented this for dataset audit trails
- If happy, we can implement on other tables as separate PRs
> #549 Provide generic tools for UI5 tables

- pom.xml
- standardization/pom.xml
- standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
With these fixes in place the end-to-end standardization of a mainframe file ran successfully.
> #568 Fix issues related to loading files in COBOL format

- menas/ui/components/auditTrail.fragment.xml
- menas/ui/components/dataset/datasetDetail.controller.js
- menas/ui/components/mappingTable/mappingTableDetail.controller.js
- menas/ui/components/schema/schemaDetail.controller.js
- Made the version link clickable instead of the whole row
- Wrapped the change details with expandable panel
> #271 Improve Audit Trail Table

- dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusDAO.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusRestDAO.scala
- standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
Thanks @GeorgiChochov for his perfect timing on `schema/export` API.
> #440 Fetch copybooks from schema attachments if not provided via cmd line

- Jenkinsfile
- conformance/pom.xml
- dao/pom.xml
- dataModel/pom.xml
- examples/pom.xml
- external/fixedWidth/pom.xml
- external/kafka/pom.xml
- menas/pom.xml
- menas/ui/components/external/it/designfuture/chartjs/library-preload.js
- menas/ui/components/home/landingPage.controller.js
- menas/ui/components/home/landingPage.view.xml
- menas/ui/components/i18n/message.properties
- migrations/pom.xml
- pom.xml
- selenium/pom.xml
- standardization/pom.xml
- testutils/pom.xml
- utils/pom.xml
> Feature/574 Prepare the project for Sonatype

- menas/src/main/resources/application.properties.template
* changing the application.properties.template suggesting the solution for application.properties
> #626: In case Menas is running on https Spline on http protocol won't load

- menas/src/main/scala/za/co/absa/enceladus/menas/controllers/RunController.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/RunService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/RunApiIntegrationSuite.scala
- menas/ui/index.html
- menas/ui/service/RestDAO.js
- menas/ui/service/RunRestDAO.js
- menas/ui/service/RunService.js
* Serialize GET requests to support the old JSON structure
* Adjust /runs GET endpoints to match the old ones
> #603 Ensure /runs GET requests are backward comaptible

- menas/ui/css/style.css
Apologies. Made an error fixing the css format, ended up pushing without `.`...
> #613 Fix missing dot in css

- menas/ui/components/app.controller.js
- menas/ui/components/login/loginDetail.controller.js
- menas/ui/components/login/loginDetail.view.xml
Also added a pubsub event for global resize.
> #637 Hamburger menu shows on login page on small width screen

- menas/ui/components/dataset/addDataset.fragment.xml
- menas/ui/components/dataset/datasetMaster.controller.js
- menas/ui/components/mappingTable/addMappingTable.fragment.xml
- menas/ui/components/mappingTable/mappingTableMaster.controller.js
- menas/ui/components/schema/selector/SchemaSelectorUtils.js
- menas/ui/components/schema/selector/schemaSelector.fragment.xml
- menas/ui/components/schema/selector/schemaSelectorDialog.fragment.xml
- menas/ui/css/style.css
- menas/ui/service/EntityDialog.js
- menas/ui/service/EntityValidationService.js
Changed sap.m.Select with sap.m.SelectDialog
> #614 Schema search when linking to new dataset

- conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
* Implementation of the column inclusion
> #610: add enceladus_info_date_string field to Conformance output

- README.md
You can take a look at the documentation here: [https://github.com/AbsaOSS/enceladus/tree/feature/update-document-on-spark-jobs](https://github.com/AbsaOSS/enceladus/tree/feature/update-document-on-spark-jobs)
> Update documentation on Standardization and Conformance jobs.

- README.md
- pom.xml
Confirmed on my local machine - the lineage is successfully saved to DB
> #704 Update Spline version to 0.3.9 to fix lineage tracking failure

- testutils/src/main/scala/za/co/absa/enceladus/testutils/DataframeReader.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/HelperFunctions.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/e2eSparkRunner/CmdConfig.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/infoFileComparison/InfoFileComparisonJob.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/rest/CmdConfig.scala
- testutils/src/main/scala/za/co/absa/enceladus/testutils/rest/RestCaller.scala
- testutils/src/test/resources/log4j.properties
* Adhere to Scalastyle
* setup logging for tests - style, filtering
> #725: Decrease the size of the build log - module Testutils

- dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusRestDAO.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/menasplugin/EventListenerMenas.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/menasplugin/MenasCredentials.scala
* Adhere to Scalastyle
* Best-practices - types declared for public members
> #743: Decrease the size of the build log - module Dao

- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
- examples/src/test/resources/log4j.properties
- examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/UppercaseCustomConformanceRuleSuite.scala
* Adhere to Scalastyle
* setup logging for tests - style, filtering
> #721: Decrease the size of the build log - module Examples

- dao/src/main/scala/za/co/absa/enceladus/dao/menasplugin/EventListenerMenas.scala
> #780 Fix duplicate run created when running Standardization

- dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusRestDAO.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/error/ErrorMessage.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/schema/SparkUtils.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkJobRunnerMethods.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkTestBase.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/validation/SchemaPathValidator.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/general/AlgorithmsSpec.scala
* Deprecated
* Really long lines
* Tags on prohibited packages and rare language features
* Scalastyle
> #783: Addressing some remaining scattered build warnings

- menas/ui/service/EntityValidationService.js
Tested on Datasets creation and Mapping Table creation. 
Schemas not properly tested because there is a Hanging PR (#832)
> 573 Fix error message for bad entity names

- migrations/src/main/scala/za/co/absa/enceladus/migrations/continuous/migrate01/DatasetMigrator.scala
- migrations/src/main/scala/za/co/absa/enceladus/migrations/migrations/MigrationToV1.scala
Thanks for the help tracking it down @Zejnilovic @yruslan and not letting me push a hacky fix.
> #842 Fix type hint replacement issue in Migrations

- migrations/src/main/scala/za/co/absa/enceladus/migrations/continuous/migrate01/DatasetMigrator.scala
- migrations/src/main/scala/za/co/absa/enceladus/migrations/migrations/MigrationToV1.scala
This time with a more appropriate regex
> #842 Use proper regex to fix type hint replacement

- README.md
- conformance/src/main/resources/application.conf.template
- conformance/src/main/scala/za/co/absa/enceladus/conformance/CmdConfig.scala
- conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- scripts/bash/run_enceladus.sh
- utils/src/main/scala/za/co/absa/enceladus/utils/fs/FileSystemVersionUtils.scala
A standardized folder is only cleaned if a Conformance job has finished successfully.
> #672 Add an option to automatically clean up standardized folder

- menas/ui/components/hdfs/HDFSBrowser.js
- menas/ui/service/EntityDialog.js
- menas/ui/service/EntityValidationService.js
Added validation for HDFS paths so users don't input special characters or characters that may make troubles for us.
> 337 Add validation for special chars in hdfs paths

- conformance/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/DropRuleInterpreter.scala
- conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/DropRuleSuite.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/schema/SchemaUtils.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/schema/SchemaUtilsSuite.scala
- added a check for the presence of a column to be dropped
- fixed previous UTs of drop rule
> 427 Add a warning message if column to drop does not exist

- menas/src/main/scala/za/co/absa/enceladus/menas/controllers/VersionedModelController.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/VersionedModelService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/SchemaApiIntegrationSuite.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
- menas/ui/components/dataset/datasetDetail.controller.js
- menas/ui/components/dataset/datasetDetail.view.xml
- menas/ui/components/mappingTable/mappingTableDetail.controller.js
- menas/ui/components/mappingTable/mappingTableDetail.view.xml
- menas/ui/components/schema/schemaDetail.controller.js
- menas/ui/components/schema/schemaDetail.view.xml
- menas/ui/service/RestDAO.js
Thought about it and instead of throwing errors around after edit, I disabled the edit button for older versions of entities.
> 220 Disable editing of old versions

- menas/ui/service/EntityValidationService.js
- HDFS path cannot be empty string
- HDFS path cannot point to root
This will also allow us to close #182
> 625 Add restrictions to HDFS path in entities

- standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_FractionalSuite.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/implicits/StructFieldImplicits.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/validation/field/FractionalFieldValidator.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/types/TypedStructFieldSuite.scala
* Read the value of allowinfinity metadata key as key and then convert to Boolean
* FieldValidator to check this metadata for fractional types
* Added UTs
> #887: allowinfinity metadata key should be a string

- dao/src/main/scala/za/co/absa/enceladus/dao/JsonSerializer.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/MenasRestDAO.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/RestClient.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/RestTemplateSingleton.scala
- dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/models/Validation.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/RunService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/RunApiIntegrationSuite.scala
WIP until I have Menas handle empy Runs.
> 945 Handle request body serialization explictly

- conformance/pom.xml
- dao/pom.xml
- dataModel/pom.xml
- examples/pom.xml
- external/fixedWidth/pom.xml
- external/kafka/pom.xml
- menas/pom.xml
- migrations-cli/pom.xml
- migrations/pom.xml
- pom.xml
- standardization/pom.xml
- standardization/src/main/resources/application.conf.template
- standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
- testutils/pom.xml
- utils/pom.xml
- utils/src/main/scala/za/co/absa/enceladus/utils/general/ConfigReader.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/time/TimeZoneNormalizer.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/types/Defaults.scala
* Definition of the two new settings for Standardization and their usage in TypeParser
* Increased project version
> #951: Global time zone setting for timestamps and dated

- conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/performance/PerformanceMetricTools.scala
Also add a couple of additional metadata fields that might be helpful in certain circumstances.
> #941 Add generic job information at the beginning of a job.

- utils/src/main/scala/za/co/absa/enceladus/utils/fs/FileSystemVersionUtils.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/performance/PerformanceMetricTools.scala
- utils/src/test/resources/test_data/test_dir/_hidden_dummy.txt
- utils/src/test/resources/test_data/test_dir/dummy.txt
- utils/src/test/resources/test_data/test_dir2/_inner_dir/_hidden_dummy.txt
- utils/src/test/resources/test_data/test_dir2/_inner_dir/dummy.txt
- utils/src/test/resources/test_data/test_dir2/dummy.txt
- utils/src/test/resources/test_data/test_dir2/inner2/dummy.txt
- utils/src/test/scala/za/co/absa/enceladus/FsUtilsSpec.scala
This adds additional metadata fields '*_data_size'.
> #968 Ignore hidden files when calculating output directory size

- pom.xml
> #1021 Upgrade java version in maven compiler source and target

- .sonarcloud.properties
- Jenkinsfile
- README.md
- pom.xml
Pom has additional SonarCloud properties required for analysis & Jenkinsfile has additional build step to run analysis.
> 1041 Updated pom & Jenkinsfile to add SonarCloud related properties/step

- menas/ui/service/EntityService.js
This only handles `Dataset` `Schema` and `Mapping Table` pages. 
`Runs` needs to be rewritten and the `Runs` navigation is unusable as is anyway. 
`Runs` will be redone in #273
> 623 Show busy indicator while loading entity master pages

- _docs/1.0.0/usage-schema.md
* Added explaining text into the documentation
* Fixed typos in link to errCol
> #1073: Unexpected schema validation error with null in default value

- _docs/1.0.0/usage-errcol.md
> #1091: Standardization error puts the sourcecolumn name into message

- menas/src/main/resources/application.properties.template
- menas/src/main/resources/scheduling/oozie/workflow_template.xml
- menas/src/main/scala/za/co/absa/enceladus/menas/repositories/OozieRepository.scala
* new setting for Spline used by Oozie
* changed Oozie template
> #1126: Spline 0.4.x in Oozie

- menas/src/main/resources/application.properties.template
- menas/src/main/resources/scheduling/oozie/workflow_template.xml
- menas/src/main/scala/za/co/absa/enceladus/menas/repositories/OozieRepository.scala
* Oozie template updated
* New shared property for *Standardization* and *Conformance* jar location
* Few code improvement suggestions
> #1154: Merge of Standardization and Conformance is not reflected in Oozie

- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/shared/error/ErrorMessageFactory.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkTestBase.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/validation/ExpressionValidator.scala
- utils/src/main/scala/za/co/absa/enceladus/utils/validation/field/FieldValidator.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/types/TypedStructFieldSuite.scala
* support to pass the array metadata to the underlying element type
* verification of metadata of array type based on the element type
> #1101: Metadata for array element types

- README.md
* `README.md` now refers the proper jar - `spark-jobs_<build_version>.jar`
> #1176: README.md refers to Conformance and Standardization jars

- dao/src/main/scala/za/co/absa/enceladus/dao/auth/MenasCredentials.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/auth/MenasCredentialsFactory.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/rest/AuthClient.scala
- dao/src/main/scala/za/co/absa/enceladus/dao/rest/RestDaoFactory.scala
- dao/src/test/scala/za/co/absa/enceladus/dao/rest/RestDaoFactorySuite.scala
- dao/src/test/scala/za/co/absa/enceladus/dao/rest/auth/MenasPlainCredentialsSuite.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
- examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
- examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/XPadCustomConformanceRuleSuite.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/EventListenerMenas.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/MenasPlugin.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConfCmdConfig.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StdCmdConfig.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/common/error/ErrorMessageFactory.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/ConfConfigSuite.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StdConfigSuite.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
Menas plugin for Atum belongs in `spark-jobs` module, not `dao`.
> #1180 Move Menas plugin for Atum to the Spark Jobs module.

- README.md
For your consideration:
* Shortened README.md entry on plugins
> * Shortened README.md entry on plugins

- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
We'll figure out if we need to calculate report date and version differently in the future.
> #1209 Make report date and version non mandatory fields.

- _docs/2.0.0/components.md
- _docs/2.0.0/plugins-built-in.md
- _docs/2.0.0/plugins.md
> 1202: More plugin checks doc

- menas/src/main/scala/za/co/absa/enceladus/menas/models/rest/errors/RequestTimeoutExpiredError.scala
> 1266: Wrong license text prevents build

- .github/CODEOWNERS
Added Adrian to gh pages CODEOWNERS
> #1258 Added Adrian in CODEOWNERS in gh pages

- .github/CODEOWNERS
> #1258 Added Adrian in CODEOWNERS

- README.md
> 1274: README.md refer to versionless documentation

- menas/src/main/scala/za/co/absa/enceladus/menas/repositories/VersionedMongoRepository.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/VersionedModelService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
Remove includeDisabled parameter
> #1142 Remove includeDisabled parameter

- data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/RunFactory.scala
- plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/factories/DceControlInfoFactory.scala
- pom.xml
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/EventListenerMenas.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/MenasPlugin.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
Merge hotfix 2.3.1 into `develop`(2.4.0-SNAPSHOT)
> Master to develop

- spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/version/SparkVersionGuard.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
Enforce minimum 2.4.3 Spark version for HyperConformance
> #1293 Add Spark version check to HyperConformance

- _posts/2020-04-27-release-2.4.0.md
* Better description of Issue #1285
> 1318: Update Release Notes of 2.4.0

- _docs/2.0.0/components.md
- _docs/2.0.0/components/menas.md
- _docs/2.0.0/usage.md
- _docs/2.0.0/usage/errcol.md
- _docs/2.0.0/usage/schema.md
- _includes/navigation.html
- _layouts/docs.html
- index.md
- utils/create_docs.rb
- utils/create_docs/docs.rb
- add new structure for docs sub-pages
- add category
- move sub-pages to a folder named same as the main page
- add breadcrumbs for docs
- move version selection to float left
- update create_docs.rb script to respect the multi-level docs.
> 1320 Add breadcrumbs to Docs

- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
> #1337 Fixing missing success case

- scripts/mongo/1347-attachment-version-off-by-one-mapping-script.js
Adding the remapping script from https://github.com/AbsaOSS/enceladus/issues/1347#issuecomment-631988013 discussion to codebase.
Relates to #1347 
@yruslan @Zejnilovic
> #1347 remapping script added

- menas/ui/components/schema/schemaDetail.controller.js
Essentially validated by Rx pattern:
```javascript
'((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|'+ // domain name
'localhost|'+ // OR localhost
'(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|'+ // OR IPv4 address
'(([0-9a-f]{0,4}:){1,7}[0-9a-f]{0,4}))' + // OR IPv6 address (simplified version, allows ::1 and short other short forms)
'(\\:\\d+)?' + // port
'(\\/[-a-z\\d%_.~+]*)*'+ // path
'(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
'(\\#[-a-z\\d_]*)?$' // fragment locator
```
After discussion with @Zejnilovic, I have not added unit tests, because the UnitTest flow setup would be out of the scope of this issue.
> #1250 URL validation

- _docs/2.0.0/plugins-built-in.md
- _docs/2.0.0/usage.md
- _docs/2.0.0/usage/info-file.md
- _docs/2.0.0/usage/run.md
- _docs/2.0.0/usage/schema.md
- _posts/2020-04-27-release-2.4.0.md
- _posts/2020-05-29-release-2.6.0.md
* Release notes for v2.6.0
* _How to run_ document
* KafkaErrorSenderPlugin built-in plugin description
* Small text improvements
> 1364: Add release notes for v2.6.0

- plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/InfoProducerKafka.scala
This happened because conversion from Java future to Scala one happens
asynchronously, so close() had a chance to execute before send()
> #1372 Fix timing issue when send() happened after close()

- _config.yml
- _docs/2.0.0/build-process.md
- _docs/2.0.0/components.md
- _docs/2.0.0/components/menas.md
- _docs/2.0.0/deployment.md
- _docs/2.0.0/plugins-built-in.md
- _docs/2.0.0/plugins.md
- _docs/2.0.0/usage.md
- _docs/2.0.0/usage/config.md
- _docs/2.0.0/usage/errcol.md
- _docs/2.0.0/usage/info-file.md
- _docs/2.0.0/usage/run.md
- _docs/2.0.0/usage/schema.md
- _docs/build-process.md
- _docs/components.md
- _docs/components/menas.md
- _docs/deployment.md
- _docs/plugins-built-in.md
- _docs/plugins.md
- _docs/usage.md
- _docs/usage/config.md
- _docs/usage/errcol.md
- _docs/usage/info-file.md
- _docs/usage/run.md
- _docs/usage/schema.md
- _layouts/redirect.html
- utils/create_docs/docs.rb
Closes 1401
Check https://github.com/AbsaOSS/gh-pages-skeleton/pull/11
> 1401 fix redirects

- scripts/bash/run_enceladus.sh
Closes #1412
RN Comment: Fix run script where the class could not be set
> 1412 Fix --class argument in run scripts

- README.md
- examples/README.md
- examples/info_files/_INFO_file_template_minimal.json
- examples/info_files/_INFO_file_template_recommended.json
INFO file minimal and recommended templates in examples.
Closes #1378
> #1378 Info file templates

- _data/menas-configuration_2_0_0.yml
- _docs/2.0.0/usage.md
- _docs/2.0.0/usage/menas-config.md
- _docs/usage/menas-config.md
Added Menas config page and related secure schema registry configuration documentation.
> #1299 menas configuration: secure schema registry

- menas/src/main/resources/application.properties.template
Just a template cleanup suggested in https://github.com/AbsaOSS/enceladus/pull/1405#discussion_r450649393.
> #1299 application.properties.template cleanup

- menas/ui/components/dataset/addDataset.fragment.xml
- menas/ui/components/mappingTable/addMappingTable.fragment.xml
- menas/ui/service/EntityDialog.js
> 1422 fix hdfs checker

- _docs/2.0.0/usage/schema.md
- _includes/image.html
> 1439 add width to schema metadata

- _docs/2.0.0/deployment.md
- _docs/2.0.0/usage/data-quick-start.md
- _docs/2.0.0/usage/menas-quick-start.md
- _docs/2.0.0/usage/spark-jobs-quick-start.md
Next in the series of quick start guides. Spark Jobs and Data quality.
> 622 quick start data and sparkjobs

- data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala
- data-model/src/test/scala/za/co/absa/enceladus/model/conformanceRule/ConformanceRuleTest.scala
- menas/ui/components/dataset/conformanceRule/CoalesceConformanceRule/add.fragment.xml
- menas/ui/components/dataset/conformanceRule/CoalesceConformanceRule/display.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConcatenationConformanceRule/add.fragment.xml
- menas/ui/components/dataset/conformanceRule/ConformanceRule.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleDialog.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js
- menas/ui/components/dataset/conformanceRule/ConformanceRuleFormFactory.js
- menas/ui/components/dataset/conformanceRule/RuleColumnDialog.fragment.xml
- menas/ui/components/dataset/conformanceRule/RuleColumnDialog.js
- menas/ui/components/dataset/conformanceRule/RuleColumnDialogFactory.js
- menas/ui/components/dataset/conformanceRule/SchemaManager.js
- menas/ui/index.html
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/CoalesceRuleInterpreter.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/CoalesceRuleSuite.scala
* coalesce rule implementation
* coalesce rule entry in UI
* UTs
Closes #1446
> 1446: Implement coalesce Conformance rule

- _config.yml
- blog/index.html
The previous fix worked with the logic of GitHub pages and did not work with the logic of paginator. 
This should be the fix. Sadly Github does not provide environment to test these on.
> Fix pagination

- _docs/2.0.0/usage/standardization-formats.md
- _posts/2020-07-24-release-2.10.0.md
- _posts/2020-07-31-release-2.10.2.md
* Add release notes for v2.10.2
* Added missing entry into Release 2.10.0 document
* fixed some typography in `standardization-formats.md`
> #1471: Add release notes for v2.10.2

- _docs/2.0.0/usage/run.md
- _docs/2.0.0/usage/spark-jobs-quick-start.md
> #1466 Updated gh-pages with combined job

- _docs/2.0.0/usage/run.md
Add documentation to support PR #1485 updating fixed-width options
> 1939 Add fixed width options

- _docs/2.0.0/usage/run.md
- _docs/2.0.0/usage/schema.md
- _docs/2.0.0/usage/standardization-formats.md
- _docs/usage/menas-conformance-rules.md
- _docs/usage/spark-jobs-quick-start.md
- _docs/usage/standardization-formats.md
- _layouts/redirect.html
- _posts/2020-10-02-release-2.14.0.md
* Release notes v2.14.0
* Fixed missing redirections
* Some typos fix
Closes #1540
> 1540: Add release notes for v2.14.0

- _data/menas-configuration_2_0_0.yml
- _docs/2.0.0/usage/menas-config.md
- _posts/2020-07-10-release-2.9.0.md
- _posts/2020-10-19-release-2.15.0.md
* Release notes for 2.15.0
* New Menas configuration options
Closes #1563
> #1563: Add release notes for v2.15.0

- _posts/2020-10-16-release-2.15.0.md
- _posts/2020-10-19-release-2.16.0.md
Release 2.15 never released
Release notes 2.15.0 renamed to the actual release 2.16.0
> Release notes 2.15.0 fix

- menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala
- pom.xml
> 1499 Make Spline in Menas work for AWS

- _docs/2.0.0/usage.md
- _docs/2.0.0/usage/menas-api.md
- _docs/usage/menas-api.md
Documentation for the Import Export
I expect we change the documentation in the audit phase but we need something to go together with the 2.17.
> 622 api export import docs

- pom.xml
* Alphabetical ordering of `pom.xml` properties
Open to opinions if this is useful or not.
> 1634: Little project fixes - optional

- menas/pom.xml
- menas/src/main/scala/za/co/absa/enceladus/menas/HDFSConfig.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala
- pom.xml
- spark-jobs/pom.xml
- spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/config/ConfigReaderSuite.scala
* Maven Shade Plugin upgraded to version 3.2.0
* Added httpclient.version and bower.chart.js.version variables to `pom.xml`
* Menas: Same origin headers
* `ConfigReaderSuite` moved to correct directory
Closes #1634
> 1634: Little project fixes

- _posts/2021-01-22-release-2.17.1.md
> 1643: Add release notes for v1.17.1

- _posts/2021-01-27-release-2.18.0.md
> 1651: Add release notes for v2.18.0

- menas/ui/components/mappingTableSelector.fragment.xml
- menas/ui/components/schema/selector/schemaSelector.fragment.xml
> #1290 Reverse ordering of versions in version pickers

- data-model/src/main/scala/za/co/absa/enceladus/model/properties/PropertyDefinition.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/PropertyDefinitionService.scala
Fixes #1659 
RN: Update and import API of Property Def now properly updates essentiality, putIntoInfoFile and propertyType
> 1659 Fix Property Definition Update

- _posts/2021-02-17-release-2.19.0.md
Release notes for Enceladus v2.19.0
> #1689 release doc for 2.19.0

- menas/ui/components/home/landingPage.controller.js
- menas/ui/components/home/landingPage.view.xml
- menas/ui/service/GenericService.js
> #1675 Add busy indicator onto the landing page of Menas

- menas/ui/components/run/runDatasetNameMaster.controller.js
- menas/ui/components/run/runDatasetVersionMaster.controller.js
- menas/ui/service/RunService.js
> #1677 Add a busy indicator onto the runs master views in Menas

- _posts/2021-02-26-release-2.20.0.md
Menas improvements only this time.
Closes #1700.
> Release notes 2.20.0

- .github/workflows/pr_labels_check.yml
Action to formalize our PR approval process a little.
The suggested labels to pass the PR are:
* `PR: tested`
* `PR: no testing needed`
* `docs` - this is a existing and widely used one
To block the PR merge:
* `PR: reviewing`
These are suggestions. Would you prefer then otherwise, comment bellow.
This is a reaction of the #1715, this one created using GitHub actions, then the workflow is better registered.
> Workflow to check labels on pull request ver.2

- utils/src/main/scala/za/co/absa/enceladus/utils/broadcast/BroadcastUtils.scala
- utils/src/test/scala/za/co/absa/enceladus/utils/broadcast/BroadcastUtilsSuite.scala
Closes #1694
Mapping rules with maximum 10 joins
> 1694 Mapping Conformance Rule with 8 or more joins

- _data/menas-configuration_2_0_0.yml
- _posts/2021-03-13-release-2.21.0.md
* Release notes for 2.21.0
* New Menas configurations added
* Menas configuration ordered alphabetically
* Cross links in Menas configuration
Closes #1722.
> #1722: Add release notes for v2.21.0

- _docs/2.0.0/usage/menas-api.md
Simple formatting fix (2x).
Before:
After:
> GHP/formatting fix in menas-api.md (tables did not render correctly)

- scripts/bash/run_enceladus.sh
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationPropertiesProvider.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/config/StandardizationConformanceConfig.scala
- spark-jobs/src/test/resources/data/standardization_csv_suite_data_with_white_spaces.csv
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/csv/WhiteSpaceStandardizationCsvSuite.scala
RN: Add an option to ignore trailing and leading white spaces on CSV read
Bash scripts enhancements to come
Closes #1753
> #1753 Add ignore white spaces option to csv read

- _docs/2.0.0/usage/menas-conformance-rules.md
> #1747 update docs for multiple mapping outputs

- _docs/2.0.0/usage/info-file.md
- _docs/2.0.0/usage/run.md
> #1760: Update documentation on CSV's ignore white space

- _posts/2021-06-28-release-2.20.2.md
- utils/resources/get_release_notes.conf.template
Release notes for v2.20.2 added to GHP.
> #1833 Release notes for v2.20.2

- dao/src/main/scala/za/co/absa/enceladus/dao/auth/MenasCredentials.scala
Closes #1814 
Replaces https://github.com/AbsaOSS/enceladus/pull/1815
> 1814 Read Menas Credentials and Keytab from S3

- menas/ui/service/EntityDialog.js
- menas/ui/service/EntityValidationService.js
* Show dialogs only on submit not in case of validation on the fly
* Show property warning only if all Mandatory has passed validation
> #1844: When saving a dataset with undefined recommended property show a warning dialog

- data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Co-authored-by: David Benedeki <14905969+benedeki@users.noreply.github.com>
> 1819 for 2.21 - Fix properties warnings not being logged in spark-jobs

- data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
- menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Co-authored-by: David Benedeki <14905969+benedeki@users.noreply.github.com>
> 1819 for 2.22.2 - Fix properties warnings not being logged in spark-jobs

- dao/pom.xml
- data-model/pom.xml
- examples/pom.xml
- menas/pom.xml
- migrations-cli/pom.xml
- migrations/pom.xml
- plugins-api/pom.xml
- plugins-builtin/pom.xml
- pom.xml
- spark-jobs/pom.xml
- utils/pom.xml
The build plugin `com.amashchenko.maven.plugin:gitflow-maven-plugin` has been updated to latest version as-of today, i.e `1.16.0`
> gitflow maven plugin update 1.16.0

- _posts/2021-07-22-release-2.22.2.md
Release notes for Enceladus 2.22.2
> #1833 Release notes for v2.22.2

- _data/configuration_2_0_0.yml
- _posts/2021-01-22-release-2.17.1.md
- _posts/2021-07-22-release-2.22.2.md
- _posts/2021-08-21-release-2.23.0.md
* Release notes
* SparkJobs settings:
** kafka.schema.registry.basic.auth.credentials.source
** kafka.schema.registry.basic.auth.user.info
> #1888: Add release notes for v2.23.0

- data-model/src/main/scala/za/co/absa/enceladus/model/SchemaField.scala
- data-model/src/test/scala/za/co/absa/enceladus/model/SchemaFieldTest.scala
- menas/src/main/scala/za/co/absa/enceladus/menas/services/MappingTableService.scala
Fixes #1903 
RN: Added function to allow importing of mapping tables with complex default values with more levels.
> 1903 Add validation for complex default values in mapping tables on import

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/poc.md
- README.md
- pom.xml
* poc issue template
* CODEOWNERS update
* developers update
> Project config and management updates

- _data/configuration_2_0_0.yml
- _posts/2021-07-22-release-2.22.2.md
- _posts/2021-09-18-release-2.24.0.md
* release notes for v2.24.0
* new configuration options `standardization.defaultTimestampTimeZone...` and`standardization.defaultDateTimeZone...`
> #1917: Add release notes for v2.24.0

- _data/configuration_2_0_0.yml
- _data/menas-configuration_2_0_0.yml
- _docs/2.0.0/usage/config.md
- _docs/2.0.0/usage/menas-config.md
> #1893 autoclean on s3

- menas/ui/components/dataset/conformanceRule/MappingConformanceRule/add.fragment.xml
- menas/ui/components/dataset/conformanceRule/MappingConformanceRule/outputColumns.fragment.xml
Closes #1966 
Relase Notes: Add missing "Add Control Checkpoint" checkbox in Mapping Table Conformance Rule
> 1966 Fix missing control checkpoint in MappingTable CR

- spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
* Correct Dataframe used for repartitioning
Closes #1974
> #1974: Conformance doesn't add the Info... columns

- _posts/2021-11-08-release-2.25.1.md
> #1976 release notes for bugfix 2.25.1

- _posts/2020-09-18-release-2.13.0.md
- _posts/2021-10-24-release-2.25.0.md
- _posts/2021-11-23-release-2.26.0.md
* Release notes for v2.26.0
* Some small fixes
Closes #1985
> #1985: Add release notes for v2.26.0

- _posts/2021-12-12-release-2.25.3.md
- _posts/2021-12-12-release-2.26.2.md
> #2001: Add release notes for v2.25.3 and v2.26.2

- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/release_notes.md
- .github/workflows/pr_labels_check.yml
* docs -> documentation
Closes #2050
> #2050: Unifying project space with GitHub defaults

- menas/ui/components/mappingTable/mappingTableDetail.view.xml
Not-well-defined XML - build problem fixing occurring in #2056.
@AdrianOlosutean
> #2042 buildfix - not well defined XML

- menas/ui/components/mappingTable/mappingTableDetail.view.xml
As @dk1844 correctly pointed out in #2057 
Closes #2058
> #2058 fix xml syntax error

- .github/CODEOWNERS
- _posts/2022-05-06-release-2.27.1.md
> #2063: Add release notes for v2.27.1

- spark-jobs/pom.xml
- spark-jobs/src/main/resources/reference.conf
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/Repartitioner.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/common/config/CommonConfConstants.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
> 2031 spark partition sizing

- examples/data/e2e_tests/setup_scripts/import_all.sh
> #2084 Fix import_all.sh for separated Menas

- .github/CODEOWNERS
- pom.xml
* CODEOWNERS updated
* developers updated
Closes #2099
> #2099: Update project maintainers and authors

- migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala
Changed:
- MongoDbIntegrationSuite.scala: Update logic to assert return document from `db.listIndexes()` call.
- Closes #2125.
> #2125 Integration test failing with MongoDB 4.4

- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationPropertiesProvider.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationCobolAsciiSuite.scala
This is to be merged into Bart's branch
> Feature/2139 fix ASCII / Cobol unit test that uses the latest Cobrix

- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
- spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
- spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationExecutionSuite.scala
> Quick merge of the fix
